2017-12-03T21:00:46.131+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9585 port=47019 dbpath=/data/shard1/rs2 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:46.131+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:46.131+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:46.131+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:46.132+0900 I CONTROL  [initandlisten] options: { net: { port: 47019 }, processManagement: { fork: true }, replication: { replSet: "s1" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard1/rs2" }, systemLog: { destination: "file", path: "s1-r2.log" } }
2017-12-03T21:00:46.153+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:46.153+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:46.153+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:46.153+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:46.224+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.224+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:46.224+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:46.224+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:46.224+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.225+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.225+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:46.225+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:46.225+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.225+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:46.249+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard1/rs2/diagnostic.data'
2017-12-03T21:00:46.270+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:46.271+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:46.271+0900 I NETWORK  [thread1] waiting for connections on port 47019
2017-12-03T21:00:51.354+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37972 #1 (1 connection now open)
2017-12-03T21:00:51.354+0900 I -        [conn1] end connection 127.0.0.1:37972 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37976 #2 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:37976 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:51.355+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-03T21:00:51.356+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.357+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37990 #3 (2 connections now open)
2017-12-03T21:00:53.357+0900 I -        [conn3] end connection 127.0.0.1:37990 (2 connections now open)
2017-12-03T21:00:53.397+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:53.471+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:53.471+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s1", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:47017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:47018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:47019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e7737da32b8ce5ce759f') } }
2017-12-03T21:00:53.471+0900 I REPL     [ReplicationExecutor] This node is localhost:47019 in the config
2017-12-03T21:00:53.471+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:53.472+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47018
2017-12-03T21:00:53.472+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-03T21:00:53.473+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47018, took 1ms (1 connections now open to localhost:47018)
2017-12-03T21:00:53.474+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state STARTUP
2017-12-03T21:00:53.475+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37994 #4 (2 connections now open)
2017-12-03T21:00:53.475+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:37994 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:53.508+0900 I REPL     [replication-0] sync source candidate: localhost:47017
2017-12-03T21:00:53.508+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:53.508+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.509+0900 I REPL     [replication-0] creating replication oplog of size: 6116MB...
2017-12-03T21:00:53.529+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:53.529+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:53.529+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:53.629+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.630+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.631+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.633+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (2 connections now open to localhost:47017)
2017-12-03T21:00:53.636+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302451000|1 })
2017-12-03T21:00:53.637+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:53.637+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302451000|1, t: -1 }[2865188406503243212]
2017-12-03T21:00:53.637+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:53.637+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302453471), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302451000|1, initialSyncOplogEnd: Timestamp 1512302451000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:53.646+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:53.646+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:53.649+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state STARTUP2
2017-12-03T21:00:53.649+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:00:58.650+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-03T21:01:03.651+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-03T21:01:08.653+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47017
2017-12-03T21:01:08.654+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:01:08.655+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (2 connections now open to localhost:47017)
2017-12-03T21:01:08.661+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38094 #5 (3 connections now open)
2017-12-03T21:01:08.661+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:38094 conn5: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:01:08.662+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38096 #6 (4 connections now open)
2017-12-03T21:01:08.663+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:38096 conn6: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.738+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38170 #7 (5 connections now open)
2017-12-03T21:02:10.738+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:38170 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.799+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.799+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.801+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.803+0900 I COMMAND  [repl writer worker 2] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.809+0900 I SHARDING [repl writer worker 13] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s1", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.809+0900 I SHARDING [repl writer worker 13] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.809+0900 I NETWORK  [repl writer worker 13] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.810+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.812+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.813+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:47019:1512302530:-41758715004048657 (sleeping for 30000ms)
2017-12-03T21:02:10.813+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.813+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.814+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.814+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.816+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 3ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.819+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.819+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.820+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.821+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.822+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.823+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.827+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.847+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38208 #8 (6 connections now open)
2017-12-03T21:02:10.847+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38236 #9 (7 connections now open)
2017-12-03T21:02:10.849+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:38208 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.851+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:38236 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.853+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:10.857+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:10.867+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38246 #10 (8 connections now open)
2017-12-03T21:02:10.868+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:38246 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.880+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38252 #11 (9 connections now open)
2017-12-03T21:02:10.881+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:38252 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38304 #12 (10 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38306 #13 (11 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:38306 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.930+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:38304 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.992+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38330 #14 (12 connections now open)
2017-12-03T21:02:10.992+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:38330 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.204+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38352 #15 (13 connections now open)
2017-12-03T21:02:11.204+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:38352 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.451+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38376 #16 (14 connections now open)
2017-12-03T21:02:27.451+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:38376 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.607+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38394 #17 (15 connections now open)
2017-12-03T21:02:27.607+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:38394 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.678+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38428 #18 (16 connections now open)
2017-12-03T21:02:40.679+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:38428 conn18: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.682+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38434 #19 (17 connections now open)
2017-12-03T21:02:40.682+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:38434 conn19: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.820+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:02:40.821+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T21:02:40.822+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.825+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.828+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.830+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:03:10.817+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.823+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:03:10.824+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:12:09.497+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:12:09.498+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-03T21:13:09.497+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:23:09.513+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:23:09.515+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-03T21:24:09.514+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:32:29.525+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:32:29.527+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-03T21:33:29.526+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:34:09.531+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:34:09.533+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-03T21:35:09.532+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:44:24.546+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:44:24.549+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 3ms (3 connections now open to localhost:47017)
2017-12-03T21:45:24.547+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:58:10.941+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:58:10.943+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:20:40.996+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:20:40.998+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:27:11.036+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:27:11.037+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T22:33:11.048+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:33:11.049+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T22:43:29.644+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T22:43:29.645+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-03T22:44:29.645+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T22:58:29.674+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T22:58:29.675+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-03T22:59:29.675+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:09:11.125+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:09:11.126+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T23:25:19.728+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T23:25:19.729+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-03T23:26:19.729+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:27:41.168+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:27:41.169+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T23:32:41.181+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:32:41.182+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T23:44:41.211+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:44:41.212+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T00:13:29.813+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T00:13:29.814+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T00:14:29.813+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T00:19:19.823+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T00:19:19.824+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T00:20:19.824+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T00:23:49.836+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T00:23:49.840+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 5ms (3 connections now open to localhost:47017)
2017-12-04T00:24:49.836+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T00:27:41.317+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:27:41.318+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T00:50:41.375+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:50:41.378+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-04T01:03:09.905+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40778 #20 (18 connections now open)
2017-12-04T01:03:09.905+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:40778 conn20: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T01:04:09.905+0900 I -        [conn6] end connection 127.0.0.1:38096 (18 connections now open)
2017-12-04T01:09:19.920+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:09:19.921+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T01:10:19.921+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:11:41.429+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:11:41.430+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T01:21:14.940+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:21:14.942+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T01:22:14.941+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:24:41.464+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:24:41.466+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T01:24:49.946+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:24:49.947+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T01:25:49.946+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:28:59.955+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:28:59.956+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T01:29:59.956+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:39:41.504+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:39:41.506+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:43:49.992+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:43:49.994+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T01:44:49.994+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:47:29.990+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:47:29.992+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T01:48:29.991+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:52:50.015+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T01:52:50.018+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 3ms (3 connections now open to localhost:47017)
2017-12-04T01:53:50.019+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T02:14:20.055+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T02:14:20.059+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 4ms (3 connections now open to localhost:47017)
2017-12-04T02:15:20.058+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T02:19:11.603+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T02:19:11.605+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T02:35:20.095+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T02:35:20.104+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 9ms (3 connections now open to localhost:47017)
2017-12-04T02:36:20.097+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T02:39:10.104+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T02:39:10.106+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T02:40:40.105+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:06:25.159+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:06:25.161+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T03:07:25.160+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:07:50.163+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:07:50.165+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T03:08:50.164+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:13:00.171+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:13:00.172+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T03:14:00.171+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:22:11.763+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:22:11.763+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-04T03:22:50.193+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:22:50.197+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 4ms (3 connections now open to localhost:47017)
2017-12-04T03:23:50.194+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:30:40.209+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:30:40.211+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T03:31:40.210+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T03:54:41.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T03:54:41.849+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-04T03:56:25.256+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T03:56:25.257+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T03:57:25.256+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:08:11.880+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T04:08:11.882+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T04:08:41.882+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:08:41.883+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T04:23:50.318+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T04:23:50.319+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T04:25:10.311+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:45:50.355+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T04:45:50.356+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T04:46:50.356+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:49:11.984+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:49:11.986+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-04T04:57:30.382+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T04:57:30.384+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T04:58:30.383+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T05:02:42.032+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:02:42.033+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T05:20:42.077+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:20:42.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T05:33:12.108+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T05:33:12.110+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T05:45:40.479+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T05:45:40.481+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T05:46:40.480+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T05:46:45.474+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T05:46:45.476+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T05:47:45.475+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T05:47:50.479+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T05:47:50.480+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T05:48:50.480+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T05:59:42.177+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:59:42.179+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-04T06:19:05.542+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T06:19:05.544+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T06:20:05.543+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T06:35:12.271+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T06:35:12.273+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T06:42:40.590+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T06:42:40.595+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 4ms (3 connections now open to localhost:47017)
2017-12-04T06:43:50.590+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T06:48:12.306+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T06:48:12.307+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T07:07:10.634+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T07:07:10.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T07:08:10.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T07:29:12.414+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T07:29:12.417+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-04T07:56:50.728+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T07:56:50.733+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 5ms (3 connections now open to localhost:47017)
2017-12-04T07:57:50.733+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T08:10:12.518+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T08:10:12.520+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T08:13:25.761+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T08:13:25.763+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-04T15:41:54.180+0900 I -        [conn5] end connection 127.0.0.1:38094 (17 connections now open)
2017-12-04T15:41:54.180+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T15:41:54.196+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.196+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.196+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T15:41:54.180+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:41:54.196+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:41:54.196+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-04T15:41:54.183+0900 I COMMAND  [conn20] command local.oplog.rs command: getMore { getMore: 34604852486, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512302451000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1 } planSummary: COLLSCAN cursorid:34604852486 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 26883418ms
2017-12-04T15:41:54.196+0900 I -        [conn20] end connection 127.0.0.1:40778 (16 connections now open)
2017-12-04T15:41:54.197+0900 I REPL     [replication-8] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 154244 -- target:localhost:47017 db:local expDate:2017-12-04T08:14:55.766+0900 cmd:{ getMore: 18148934450, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342825000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342825000|1, t: 1 }[5334871594228210341]. Restarts remaining: 3
2017-12-04T15:41:54.197+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T15:41:54.197+0900 I REPL     [replication-8] Scheduled new oplog query Fetcher source: localhost:47017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 154264 -- target:localhost:47017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:47018; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:41:54.202+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47018 with reason "already voted for another candidate this term"; response message: { term: 2, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-04T15:41:54.205+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47017 with reason "candidate's data is staler than mine"; response message: { term: 2, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-04T15:41:54.206+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-04T15:41:54.209+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42278 #21 (16 connections now open)
2017-12-04T15:41:54.209+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42280 #22 (17 connections now open)
2017-12-04T15:41:54.209+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42286 #23 (18 connections now open)
2017-12-04T15:41:54.210+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:42286 conn23: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:54.210+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:42278 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:54.210+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:42280 conn22: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:54.211+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.211+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.211+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 15ms (2 connections now open to localhost:47017)
2017-12-04T15:41:54.211+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 14ms (2 connections now open to localhost:47017)
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 16ms (2 connections now open to localhost:47017)
2017-12-04T15:41:54.223+0900 I REPL     [replication-7] Choosing new sync source because our current sync source, localhost:47017, has an OpTime ({ ts: Timestamp 1512369714000|1, t: 1 }) which is not ahead of ours ({ ts: Timestamp 1512369714000|1, t: 1 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T15:41:54.223+0900 I REPL     [replication-7] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47017, OpTime { ts: Timestamp 1512369714000|1, t: 1 }, its sync source index:-1
2017-12-04T15:41:54.223+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47017 (config version: 1; last applied optime: { ts: Timestamp 1512369714000|1, t: 1 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T15:41:54.223+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T15:41:54.224+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-04T15:41:54.226+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47017: InvalidSyncSource: Sync source was cleared. Was localhost:47017
2017-12-04T15:42:04.617+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:42:04.617+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:42:04.620+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2 dry run) received a yes vote from localhost:47017; response message: { term: 2, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:42:04.620+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:42:04.636+0900 I REPL     [ReplicationExecutor] VoteRequester(term 3) received a yes vote from localhost:47017; response message: { term: 3, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:42:04.636+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 3
2017-12-04T15:42:04.637+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-04T15:42:04.637+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-04T15:42:04.637+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47018
2017-12-04T15:42:04.638+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host localhost:47018 due to bad connection status; 1 connections to that host remain open
2017-12-04T15:42:04.641+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47018, took 4ms (1 connections now open to localhost:47018)
2017-12-04T15:42:04.642+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-04T15:42:04.642+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-04T15:42:06.224+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-04T15:42:07.242+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42360 #24 (19 connections now open)
2017-12-04T15:42:07.242+0900 I NETWORK  [conn24] received client metadata from 127.0.0.1:42360 conn24: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:10.464+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:10.466+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T15:42:10.837+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.839+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.841+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.842+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.844+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.845+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:10.847+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.849+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:12.182+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42462 #25 (20 connections now open)
2017-12-04T15:42:12.182+0900 I NETWORK  [conn25] received client metadata from 127.0.0.1:42462 conn25: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:12.185+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42464 #26 (21 connections now open)
2017-12-04T15:42:12.185+0900 I NETWORK  [conn26] received client metadata from 127.0.0.1:42464 conn26: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:54.203+0900 I -        [conn4] end connection 127.0.0.1:37994 (21 connections now open)
2017-12-04T15:42:54.206+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.222+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:44:10.470+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:44:10.471+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T15:45:05.734+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42506 #27 (21 connections now open)
2017-12-04T15:45:05.735+0900 I NETWORK  [conn27] received client metadata from 127.0.0.1:42506 conn27: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:45:05.746+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42508 #28 (22 connections now open)
2017-12-04T15:45:05.746+0900 I NETWORK  [conn28] received client metadata from 127.0.0.1:42508 conn28: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:45:51.173+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42816 #29 (23 connections now open)
2017-12-04T15:45:51.173+0900 I NETWORK  [conn29] received client metadata from 127.0.0.1:42816 conn29: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:48:00.200+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43870 #30 (24 connections now open)
2017-12-04T15:48:00.203+0900 I NETWORK  [conn30] received client metadata from 127.0.0.1:43870 conn30: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:48:07.358+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43934 #31 (25 connections now open)
2017-12-04T15:48:07.358+0900 I NETWORK  [conn31] received client metadata from 127.0.0.1:43934 conn31: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:50:05.747+0900 I -        [conn28] end connection 127.0.0.1:42508 (25 connections now open)
2017-12-04T15:50:51.176+0900 I -        [conn29] end connection 127.0.0.1:42816 (24 connections now open)
2017-12-04T15:52:06.688+0900 I COMMAND  [conn21] command local.oplog.rs command: getMore { getMore: 35554011462, collection: "oplog.rs", maxTimeMS: 5000, term: 3, lastKnownCommittedOpTime: { ts: Timestamp 1512370316000|1, t: 3 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 3, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:35554011462 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 5438ms
2017-12-04T15:52:06.700+0900 I COMMAND  [conn25] command local.oplog.rs command: getMore { getMore: 34539207195, collection: "oplog.rs", maxTimeMS: 5000, term: 3, lastKnownCommittedOpTime: { ts: Timestamp 1512370316000|1, t: 3 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 3, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:34539207195 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 5450ms
2017-12-04T15:56:22.459+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44438 #32 (24 connections now open)
2017-12-04T15:56:22.459+0900 I NETWORK  [conn32] received client metadata from 127.0.0.1:44438 conn32: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:56:46.913+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44648 #33 (25 connections now open)
2017-12-04T15:56:46.914+0900 I NETWORK  [conn33] received client metadata from 127.0.0.1:44648 conn33: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:59:53.353+0900 I -        [conn31] end connection 127.0.0.1:43934 (25 connections now open)
2017-12-04T15:59:59.603+0900 I -        [conn30] end connection 127.0.0.1:43870 (24 connections now open)
2017-12-04T16:00:38.099+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46572 #34 (24 connections now open)
2017-12-04T16:00:38.100+0900 I NETWORK  [conn34] received client metadata from 127.0.0.1:46572 conn34: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:01:22.460+0900 I -        [conn32] end connection 127.0.0.1:44438 (24 connections now open)
2017-12-04T16:01:46.916+0900 I -        [conn33] end connection 127.0.0.1:44648 (23 connections now open)
2017-12-04T16:04:40.552+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:48544 #35 (23 connections now open)
2017-12-04T16:04:40.552+0900 I NETWORK  [conn35] received client metadata from 127.0.0.1:48544 conn35: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:06:41.256+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:06:41.257+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T16:13:30.549+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52946 #36 (24 connections now open)
2017-12-04T16:13:30.549+0900 I NETWORK  [conn36] received client metadata from 127.0.0.1:52946 conn36: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:13:57.292+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:53170 #37 (25 connections now open)
2017-12-04T16:13:57.292+0900 I NETWORK  [conn37] received client metadata from 127.0.0.1:53170 conn37: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:17:32.410+0900 I -        [conn34] end connection 127.0.0.1:46572 (25 connections now open)
2017-12-04T16:17:38.934+0900 I -        [conn35] end connection 127.0.0.1:48544 (24 connections now open)
2017-12-04T16:19:41.282+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:19:41.283+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T16:21:34.208+0900 I -        [conn36] end connection 127.0.0.1:52946 (23 connections now open)
2017-12-04T16:21:36.102+0900 I -        [conn37] end connection 127.0.0.1:53170 (22 connections now open)
2017-12-04T16:45:25.183+0900 I COMMAND  [conn26] command local.oplog.rs command: getMore { getMore: 34539207195, collection: "oplog.rs", maxTimeMS: 5000, term: 3, lastKnownCommittedOpTime: { ts: Timestamp 1512372446000|1, t: 3 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 3, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:34539207195 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 1073426ms
2017-12-04T16:45:25.183+0900 I COMMAND  [conn21] command local.oplog.rs command: getMore { getMore: 35554011462, collection: "oplog.rs", maxTimeMS: 5000, term: 3, lastKnownCommittedOpTime: { ts: Timestamp 1512372446000|1, t: 3 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 3, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:35554011462 keysExamined:0 docsExamined:1 numYields:1 nreturned:1 reslen:662 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 1073427ms
2017-12-04T16:45:25.185+0900 I REPL     [ReplicationExecutor] can't see a majority of the set, relinquishing primary
2017-12-04T16:45:25.185+0900 I REPL     [ReplicationExecutor] Stepping down from primary in response to heartbeat
2017-12-04T16:45:25.185+0900 I REPL     [replExecDBWorker-0] transition to SECONDARY
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 26
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 25
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 24
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 23
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 22
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 21
2017-12-04T16:45:25.186+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 2
2017-12-04T16:45:25.186+0900 I -        [conn11] end connection 127.0.0.1:38252 (21 connections now open)
2017-12-04T16:45:25.186+0900 I -        [conn7] end connection 127.0.0.1:38170 (20 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn10] end connection 127.0.0.1:38246 (19 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn16] end connection 127.0.0.1:38376 (18 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn19] end connection 127.0.0.1:38434 (17 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn18] end connection 127.0.0.1:38428 (16 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn8] end connection 127.0.0.1:38208 (15 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn14] end connection 127.0.0.1:38330 (14 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn12] end connection 127.0.0.1:38304 (13 connections now open)
2017-12-04T16:45:25.188+0900 I -        [conn15] end connection 127.0.0.1:38352 (12 connections now open)
2017-12-04T16:45:25.189+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-04T16:45:25.190+0900 I -        [conn9] end connection 127.0.0.1:38236 (11 connections now open)
2017-12-04T16:45:25.190+0900 I -        [conn13] end connection 127.0.0.1:38306 (10 connections now open)
2017-12-04T16:45:25.190+0900 I -        [conn17] end connection 127.0.0.1:38394 (9 connections now open)
2017-12-04T16:45:25.190+0900 I -        [conn27] end connection 127.0.0.1:42506 (8 connections now open)
2017-12-04T16:45:25.194+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-04T16:45:25.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:37018)
2017-12-04T16:45:25.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:47019)
2017-12-04T16:45:25.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:57019)
2017-12-04T16:45:25.256+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.256+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:27.350+0900 I -        [conn25] end connection 127.0.0.1:42462 (7 connections now open)
2017-12-04T16:45:31.203+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60224 #38 (7 connections now open)
2017-12-04T16:45:31.204+0900 I NETWORK  [conn38] received client metadata from 127.0.0.1:60224 conn38: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:31.892+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:45:31.894+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T16:45:32.014+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60262 #39 (8 connections now open)
2017-12-04T16:45:32.014+0900 I NETWORK  [conn39] received client metadata from 127.0.0.1:60262 conn39: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.029+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60280 #40 (9 connections now open)
2017-12-04T16:45:32.029+0900 I NETWORK  [conn40] received client metadata from 127.0.0.1:60280 conn40: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60282 #41 (10 connections now open)
2017-12-04T16:45:32.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60284 #42 (11 connections now open)
2017-12-04T16:45:32.030+0900 I NETWORK  [conn41] received client metadata from 127.0.0.1:60282 conn41: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.030+0900 I NETWORK  [conn42] received client metadata from 127.0.0.1:60284 conn42: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.303+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57041)
2017-12-04T16:45:32.305+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-04T16:45:32.307+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-04T16:45:32.309+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60312 #43 (12 connections now open)
2017-12-04T16:45:32.310+0900 I NETWORK  [conn43] received client metadata from 127.0.0.1:60312 conn43: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.310+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-04T16:45:32.312+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60318 #44 (13 connections now open)
2017-12-04T16:45:32.312+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60320 #45 (14 connections now open)
2017-12-04T16:45:32.312+0900 I NETWORK  [conn44] received client metadata from 127.0.0.1:60318 conn44: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.313+0900 I NETWORK  [conn45] received client metadata from 127.0.0.1:60320 conn45: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.313+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-04T16:45:32.314+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-04T16:45:32.333+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60328 #46 (15 connections now open)
2017-12-04T16:45:32.333+0900 I NETWORK  [conn46] received client metadata from 127.0.0.1:60328 conn46: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.333+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60332 #47 (16 connections now open)
2017-12-04T16:45:32.334+0900 I NETWORK  [conn47] received client metadata from 127.0.0.1:60332 conn47: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.341+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60342 #48 (17 connections now open)
2017-12-04T16:45:32.341+0900 I NETWORK  [conn48] received client metadata from 127.0.0.1:60342 conn48: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.192+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state PRIMARY
2017-12-04T16:45:40.194+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47018
2017-12-04T16:45:40.194+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-04T16:45:40.195+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 1ms (1 connections now open to localhost:47018)
2017-12-04T16:45:40.196+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-04T16:45:40.197+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 1ms (2 connections now open to localhost:47018)
2017-12-04T16:45:48.931+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60490 #49 (18 connections now open)
2017-12-04T16:45:48.931+0900 I NETWORK  [conn49] received client metadata from 127.0.0.1:60490 conn49: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:49.060+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60498 #50 (19 connections now open)
2017-12-04T16:45:49.060+0900 I NETWORK  [conn50] received client metadata from 127.0.0.1:60498 conn50: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:49.452+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60510 #51 (20 connections now open)
2017-12-04T16:45:49.453+0900 I NETWORK  [conn51] received client metadata from 127.0.0.1:60510 conn51: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:55.257+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:45:55.259+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T16:46:25.219+0900 I -        [conn22] end connection 127.0.0.1:42280 (20 connections now open)
2017-12-04T16:50:25.216+0900 I -        [conn24] end connection 127.0.0.1:42360 (19 connections now open)
2017-12-04T16:50:25.252+0900 I -        [conn26] end connection 127.0.0.1:42464 (18 connections now open)
2017-12-04T16:50:30.219+0900 I -        [conn21] end connection 127.0.0.1:42278 (17 connections now open)
2017-12-04T16:50:41.225+0900 I -        [conn38] end connection 127.0.0.1:60224 (16 connections now open)
2017-12-04T17:42:33.033+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T17:42:33.036+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-04T17:49:33.050+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T17:49:33.052+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T17:50:04.189+0900 I INDEX    [repl writer worker 1] build index on: mongomart.item properties: { v: 2, key: { _fts: "text", _ftsx: 1 }, name: "title_text_slogan_text_description_text", ns: "mongomart.item", weights: { description: 1, slogan: 1, title: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 }
2017-12-04T17:50:04.189+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-04T17:50:04.202+0900 I INDEX    [repl writer worker 1] build index done.  scanned 23 total records. 0 secs
2017-12-04T18:52:33.189+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T18:52:33.190+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T19:13:57.193+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 144 secs, remote host 127.0.0.1:47018)
2017-12-04T19:13:57.193+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 144 secs, remote host 127.0.0.1:57017)
2017-12-04T19:13:57.194+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-04T19:13:57.250+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T19:13:57.251+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T19:14:02.199+0900 I REPL     [replication-10] Choosing new sync source because our current sync source, localhost:47018, has an OpTime ({ ts: Timestamp 1512382437000|1, t: 4 }) which is not ahead of ours ({ ts: Timestamp 1512382437000|1, t: 4 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T19:14:02.199+0900 I REPL     [replication-10] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47018, OpTime { ts: Timestamp 1512382437000|1, t: 4 }, its sync source index:-1
2017-12-04T19:14:02.199+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47018 (config version: 1; last applied optime: { ts: Timestamp 1512382437000|1, t: 4 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T19:14:02.199+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T19:14:02.251+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47018: InvalidSyncSource: Sync source was cleared. Was localhost:47018
2017-12-04T19:14:12.201+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-04T19:14:12.202+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47017
2017-12-04T19:14:12.202+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T19:14:12.204+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (1 connections now open to localhost:47017)
2017-12-04T19:14:12.206+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T19:14:12.208+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (2 connections now open to localhost:47017)
2017-12-04T19:14:20.924+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:57042)
2017-12-04T19:14:20.926+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-04T19:14:20.929+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T19:14:20.931+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:37017)
2017-12-04T19:14:20.933+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T19:14:20.936+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-04T19:14:57.251+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T20:06:29.327+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T20:06:29.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T20:07:29.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T21:26:51.434+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T21:26:51.435+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T21:31:21.443+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:31:21.445+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T21:41:51.471+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:41:51.475+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-04T22:04:51.535+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T22:04:51.537+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T22:33:51.609+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T22:33:51.611+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T23:26:51.745+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T23:26:51.746+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T23:29:21.753+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T23:29:21.755+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T23:47:51.805+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T23:47:51.807+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T23:59:21.837+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T23:59:21.838+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T00:17:51.884+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T00:17:51.886+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T00:21:51.896+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:21:51.897+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:08:59.882+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T01:08:59.884+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-05T01:09:59.884+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T01:14:24.893+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T01:14:24.897+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 4ms (3 connections now open to localhost:47017)
2017-12-05T01:15:24.896+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T01:24:22.050+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T01:24:22.051+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T02:21:22.180+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:21:22.181+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T02:41:22.229+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:41:22.230+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T03:17:52.316+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:17:52.318+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T03:57:22.409+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:57:22.413+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T04:21:22.470+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T04:21:22.472+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T04:55:22.556+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:55:22.558+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T06:12:22.720+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T06:12:22.721+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:22:22.740+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T06:22:22.741+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:38:52.779+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T06:38:52.781+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T06:46:50.507+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T06:46:50.509+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (3 connections now open to localhost:47017)
2017-12-05T06:47:50.507+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T06:56:52.813+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T06:56:52.814+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T07:28:22.883+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T07:28:22.885+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T07:43:52.915+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T07:43:52.917+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T07:58:22.948+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T07:58:22.951+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-05T15:30:53.176+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:30:53.176+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.182+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T15:30:53.182+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:47017)
2017-12-05T15:30:53.182+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T15:30:53.182+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T15:30:53.183+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-05T15:30:53.183+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47018
2017-12-05T15:30:53.183+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5 dry run) received a yes vote from localhost:47018; response message: { term: 5, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T15:30:53.183+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T15:30:53.183+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47018, took 1ms (2 connections now open to localhost:47018)
2017-12-05T15:30:53.185+0900 I REPL     [replication-13] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 343500 -- target:localhost:47017 db:local expDate:2017-12-05T08:05:35.644+0900 cmd:{ getMore: 17746931724, collection: "oplog.rs", maxTimeMS: 5000, term: 5, lastKnownCommittedOpTime: { ts: Timestamp 1512428670000|1, t: 5 } }. Last fetched optime (with hash): { ts: Timestamp 1512428670000|1, t: 5 }[-3228870133416877210]. Restarts remaining: 3
2017-12-05T15:30:53.185+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T15:30:53.190+0900 I REPL     [replication-13] Scheduled new oplog query Fetcher source: localhost:47017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 343521 -- target:localhost:47017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-05T15:30:53.206+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-05T15:30:53.218+0900 I REPL     [ReplicationExecutor] VoteRequester(term 6) received a yes vote from localhost:47018; response message: { term: 6, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T15:30:53.218+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 6
2017-12-05T15:30:53.218+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-05T15:30:53.218+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-05T15:30:53.218+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-05T15:30:53.218+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host localhost:47017 due to bad connection status; 3 connections to that host remain open
2017-12-05T15:30:53.241+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 59ms (2 connections now open to localhost:47017)
2017-12-05T15:30:53.243+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 58ms (2 connections now open to localhost:47017)
2017-12-05T15:30:53.244+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-05T15:30:53.244+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-05T15:30:53.245+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 39ms (3 connections now open to localhost:47017)
2017-12-05T15:30:53.245+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 27ms (3 connections now open to localhost:47017)
2017-12-05T15:30:53.245+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512428670000|1, t: 5 } is not greater than our last fetched OpTime { ts: Timestamp 1512428670000|1, t: 5 }. Choosing new sync source.
2017-12-05T15:30:53.245+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-05T15:30:53.245+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-05T15:30:53.245+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-05T15:30:53.246+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 64ms (3 connections now open to localhost:47017)
2017-12-05T15:30:55.176+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-05T15:30:56.177+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54522 #52 (16 connections now open)
2017-12-05T15:30:56.177+0900 I NETWORK  [conn52] received client metadata from 127.0.0.1:54522 conn52: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:56.181+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54524 #53 (17 connections now open)
2017-12-05T15:30:56.181+0900 I NETWORK  [conn53] received client metadata from 127.0.0.1:54524 conn53: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:58.246+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47017: InvalidSyncSource: Sync source was cleared. Was localhost:47017
2017-12-05T15:30:58.252+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54564 #54 (18 connections now open)
2017-12-05T15:30:58.252+0900 I NETWORK  [conn54] received client metadata from 127.0.0.1:54564 conn54: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:58.255+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54566 #55 (19 connections now open)
2017-12-05T15:30:58.255+0900 I NETWORK  [conn55] received client metadata from 127.0.0.1:54566 conn55: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:31:09.227+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T15:31:09.230+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 3ms (1 connections now open to localhost:57040)
2017-12-05T15:31:10.044+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 17 secs, remote host 127.0.0.1:57041)
2017-12-05T15:31:10.047+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-05T15:31:10.048+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 17 secs, remote host 127.0.0.1:37019)
2017-12-05T15:31:10.050+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-05T15:31:10.052+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 17 secs, remote host 127.0.0.1:57017)
2017-12-05T15:31:10.053+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T15:31:10.055+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-05T15:31:16.228+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54802 #56 (20 connections now open)
2017-12-05T15:31:16.229+0900 I NETWORK  [conn56] received client metadata from 127.0.0.1:54802 conn56: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:31:53.184+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.246+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T15:31:53.246+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.246+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:32:09.233+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T15:32:09.234+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T16:03:27.184+0900 I REPL     [ReplicationExecutor] can't see a majority of the set, relinquishing primary
2017-12-05T16:03:27.184+0900 I REPL     [ReplicationExecutor] Stepping down from primary in response to heartbeat
2017-12-05T16:03:27.184+0900 I REPL     [replExecDBWorker-2] transition to SECONDARY
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] legacy transport layer closing all connections
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 56
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 55
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 54
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 53
2017-12-05T16:03:27.184+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 52
2017-12-05T16:03:27.185+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 23
2017-12-05T16:03:27.185+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 2
2017-12-05T16:03:27.185+0900 I -        [conn46] end connection 127.0.0.1:60328 (20 connections now open)
2017-12-05T16:03:27.188+0900 I -        [conn50] end connection 127.0.0.1:60498 (19 connections now open)
2017-12-05T16:03:27.192+0900 I -        [conn49] end connection 127.0.0.1:60490 (18 connections now open)
2017-12-05T16:03:27.193+0900 I -        [conn48] end connection 127.0.0.1:60342 (17 connections now open)
2017-12-05T16:03:27.193+0900 I -        [conn42] end connection 127.0.0.1:60284 (16 connections now open)
2017-12-05T16:03:27.193+0900 I -        [conn45] end connection 127.0.0.1:60320 (15 connections now open)
2017-12-05T16:03:27.195+0900 I -        [conn41] end connection 127.0.0.1:60282 (14 connections now open)
2017-12-05T16:03:27.197+0900 I -        [conn47] end connection 127.0.0.1:60332 (13 connections now open)
2017-12-05T16:03:27.197+0900 I -        [conn44] end connection 127.0.0.1:60318 (12 connections now open)
2017-12-05T16:03:27.197+0900 I -        [conn40] end connection 127.0.0.1:60280 (11 connections now open)
2017-12-05T16:03:27.197+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58206 #57 (8 connections now open)
2017-12-05T16:03:27.198+0900 I NETWORK  [conn57] received client metadata from 127.0.0.1:58206 conn57: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.198+0900 I -        [conn51] end connection 127.0.0.1:60510 (11 connections now open)
2017-12-05T16:03:27.198+0900 I -        [conn39] end connection 127.0.0.1:60262 (10 connections now open)
2017-12-05T16:03:27.198+0900 I -        [conn43] end connection 127.0.0.1:60312 (9 connections now open)
2017-12-05T16:03:27.208+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:37017)
2017-12-05T16:03:27.208+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:47019)
2017-12-05T16:03:27.208+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:57018)
2017-12-05T16:03:27.209+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58228 #58 (9 connections now open)
2017-12-05T16:03:27.209+0900 I NETWORK  [conn58] received client metadata from 127.0.0.1:58228 conn58: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.214+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58232 #59 (10 connections now open)
2017-12-05T16:03:27.214+0900 I NETWORK  [conn59] received client metadata from 127.0.0.1:58232 conn59: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.230+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-05T16:03:27.230+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-05T16:03:27.230+0900 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 1514454, after security: 1514454, after storageEngine: 1514454, after tcmalloc: 1514454, after wiredTiger: 1514454, at end: 1514454 }
2017-12-05T16:03:27.231+0900 I COMMAND  [conn55] command local.oplog.rs command: getMore { getMore: 35959852714, collection: "oplog.rs", maxTimeMS: 5000, term: 6, lastKnownCommittedOpTime: { ts: Timestamp 1512455885000|1, t: 6 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 6, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } planSummary: COLLSCAN cursorid:35959852714 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 3967 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1517033ms
2017-12-05T16:03:27.235+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: NotMaster: not master
2017-12-05T16:03:27.237+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512369730837888 microSec, clearing pool for localhost:57040 of 0 connections
2017-12-05T16:03:27.237+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57040(with timeout of 5 seconds)
2017-12-05T16:03:27.237+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57040(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-05T16:03:27.237+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:27.238+0900 I COMMAND  [conn53] command local.oplog.rs command: getMore { getMore: 38217046622, collection: "oplog.rs", maxTimeMS: 5000, term: 6, lastKnownCommittedOpTime: { ts: Timestamp 1512455885000|1, t: 6 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 6, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } planSummary: COLLSCAN cursorid:38217046622 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 29253 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1517041ms
2017-12-05T16:03:27.249+0900 I -        [conn23] end connection 127.0.0.1:42286 (10 connections now open)
2017-12-05T16:03:27.668+0900 I -        [conn54] end connection 127.0.0.1:54564 (9 connections now open)
2017-12-05T16:03:27.669+0900 I -        [conn52] end connection 127.0.0.1:54522 (8 connections now open)
2017-12-05T16:03:27.738+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-05T16:03:27.738+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:29.234+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58284 #60 (8 connections now open)
2017-12-05T16:03:29.234+0900 I NETWORK  [conn60] received client metadata from 127.0.0.1:58284 conn60: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:32.230+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state PRIMARY
2017-12-05T16:03:32.231+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47018
2017-12-05T16:03:32.231+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-05T16:03:32.232+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 1ms (1 connections now open to localhost:47018)
2017-12-05T16:03:32.234+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-05T16:03:32.236+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (2 connections now open to localhost:47018)
2017-12-05T16:03:33.254+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58334 #61 (9 connections now open)
2017-12-05T16:03:33.255+0900 I NETWORK  [conn61] received client metadata from 127.0.0.1:58334 conn61: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.313+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58392 #62 (10 connections now open)
2017-12-05T16:03:39.314+0900 I NETWORK  [conn62] received client metadata from 127.0.0.1:58392 conn62: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.447+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58400 #63 (11 connections now open)
2017-12-05T16:03:39.448+0900 I NETWORK  [conn63] received client metadata from 127.0.0.1:58400 conn63: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.480+0900 I -        [conn56] end connection 127.0.0.1:54802 (11 connections now open)
2017-12-05T16:03:39.940+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58408 #64 (11 connections now open)
2017-12-05T16:03:39.940+0900 I NETWORK  [conn64] received client metadata from 127.0.0.1:58408 conn64: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.146+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58530 #65 (12 connections now open)
2017-12-05T16:03:52.147+0900 I NETWORK  [conn65] received client metadata from 127.0.0.1:58530 conn65: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.155+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58540 #66 (13 connections now open)
2017-12-05T16:03:52.155+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58542 #67 (14 connections now open)
2017-12-05T16:03:52.156+0900 I NETWORK  [conn66] received client metadata from 127.0.0.1:58540 conn66: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.156+0900 I NETWORK  [conn67] received client metadata from 127.0.0.1:58542 conn67: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.159+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58544 #68 (15 connections now open)
2017-12-05T16:03:52.160+0900 I NETWORK  [conn68] received client metadata from 127.0.0.1:58544 conn68: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.489+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58558 #69 (16 connections now open)
2017-12-05T16:03:52.489+0900 I NETWORK  [conn69] received client metadata from 127.0.0.1:58558 conn69: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.491+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58562 #70 (17 connections now open)
2017-12-05T16:03:52.492+0900 I NETWORK  [conn70] received client metadata from 127.0.0.1:58562 conn70: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.539+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58572 #71 (18 connections now open)
2017-12-05T16:03:52.540+0900 I NETWORK  [conn71] received client metadata from 127.0.0.1:58572 conn71: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.540+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-05T16:03:52.543+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58580 #72 (19 connections now open)
2017-12-05T16:03:52.544+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-05T16:03:52.544+0900 I NETWORK  [conn72] received client metadata from 127.0.0.1:58580 conn72: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.544+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58582 #73 (20 connections now open)
2017-12-05T16:03:52.545+0900 I NETWORK  [conn73] received client metadata from 127.0.0.1:58582 conn73: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.546+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:58586 #74 (21 connections now open)
2017-12-05T16:03:52.546+0900 I NETWORK  [conn74] received client metadata from 127.0.0.1:58586 conn74: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.547+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-05T16:04:21.726+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-05T16:04:21.728+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-05T16:04:27.249+0900 I -        [conn59] end connection 127.0.0.1:58232 (21 connections now open)
2017-12-05T16:04:27.249+0900 I -        [conn58] end connection 127.0.0.1:58228 (20 connections now open)
2017-12-05T16:05:59.201+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-05T16:05:59.203+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (3 connections now open to localhost:47018)
2017-12-05T16:06:59.203+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T16:08:27.249+0900 I -        [conn55] end connection 127.0.0.1:54566 (19 connections now open)
2017-12-05T16:08:39.266+0900 I -        [conn60] end connection 127.0.0.1:58284 (18 connections now open)
2017-12-05T16:09:23.028+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T16:09:23.029+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T17:08:56.193+0900 I COMMAND  [conn53] command local.oplog.rs command: getMore { getMore: 35987437854, collection: "oplog.rs", maxTimeMS: 5000, term: 7, lastKnownCommittedOpTime: { ts: Timestamp 1512458979000|1, t: 7 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512455885000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 7, readConcern: { afterOpTime: { ts: Timestamp 1512455885000|1, t: 6 } } } planSummary: COLLSCAN cursorid:35987437854 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 2351942ms
2017-12-05T17:08:56.210+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 2373 secs, remote host 127.0.0.1:57017)
2017-12-05T17:08:56.210+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 2373 secs, remote host 127.0.0.1:57042)
2017-12-05T17:08:56.222+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: NotMaster: not master
2017-12-05T17:08:56.227+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-05T17:08:56.229+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:08:56.240+0900 I REPL     [replication-10] Choosing new sync source because our current sync source, localhost:47018, has an OpTime ({ ts: Timestamp 1512461336000|1, t: 7 }) which is not ahead of ours ({ ts: Timestamp 1512461336000|1, t: 7 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-05T17:08:56.240+0900 I REPL     [replication-10] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47018, OpTime { ts: Timestamp 1512461336000|1, t: 7 }, its sync source index:-1
2017-12-05T17:08:56.240+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47018 (config version: 1; last applied optime: { ts: Timestamp 1512461336000|1, t: 7 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-05T17:08:56.241+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-05T17:08:56.241+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-05T17:08:56.242+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47018: InvalidSyncSource: Sync source was cleared. Was localhost:47018
2017-12-05T17:08:56.733+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:08:57.235+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:08:57.762+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T17:09:01.586+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:09:01.588+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T17:09:02.415+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T17:09:02.416+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s2
2017-12-05T17:09:02.416+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 6 secs, remote host 127.0.0.1:47018)
2017-12-05T17:09:02.417+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-05T17:09:02.418+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-05T17:09:06.317+0900 I -        [conn57] end connection 127.0.0.1:58206 (17 connections now open)
2017-12-05T17:09:06.317+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42402 #75 (17 connections now open)
2017-12-05T17:09:06.318+0900 I NETWORK  [conn75] received client metadata from 127.0.0.1:42402 conn75: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T17:09:11.244+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state PRIMARY
2017-12-05T17:09:11.245+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47018
2017-12-05T17:09:11.246+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-05T17:09:11.248+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (2 connections now open to localhost:47018)
2017-12-05T17:09:56.245+0900 I -        [conn61] end connection 127.0.0.1:58334 (17 connections now open)
2017-12-05T17:14:01.244+0900 I -        [conn53] end connection 127.0.0.1:54524 (16 connections now open)
2017-12-05T17:14:31.599+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:14:31.599+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T17:50:32.301+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:50:32.305+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T17:59:02.325+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:59:02.327+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T18:04:32.338+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T18:04:32.339+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T18:15:02.357+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T18:15:02.359+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T18:28:32.382+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T18:28:32.383+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T18:53:32.445+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T18:53:32.446+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T19:38:02.559+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T19:38:02.561+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T20:11:32.638+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T20:11:32.639+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T20:22:02.667+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T20:22:02.668+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T20:37:32.711+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T20:37:32.715+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-05T21:10:02.789+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T21:10:02.791+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T21:55:32.899+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T21:55:32.903+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T22:44:03.020+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T22:44:03.021+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T23:19:03.070+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T23:19:03.072+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T00:01:33.179+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T00:01:33.180+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T00:28:33.246+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T00:28:33.248+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T00:35:38.965+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T00:35:38.967+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (3 connections now open to localhost:47018)
2017-12-06T00:36:38.966+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T00:38:03.272+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T00:38:03.274+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T01:16:34.051+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T01:16:34.053+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (3 connections now open to localhost:47018)
2017-12-06T01:17:34.051+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T01:21:19.057+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T01:21:19.058+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (3 connections now open to localhost:47018)
2017-12-06T01:22:19.057+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T01:34:03.415+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T01:34:03.417+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T02:01:33.486+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T02:01:33.488+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T02:36:03.581+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T02:36:03.585+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-06T02:48:33.613+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T02:48:33.614+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T03:23:33.702+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T03:23:33.704+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T03:25:33.708+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T03:25:33.709+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T03:47:33.761+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T03:47:33.765+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-06T04:00:33.792+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:00:33.794+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T04:08:33.813+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:08:33.814+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T04:21:03.844+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:21:03.846+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T04:39:33.892+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:39:33.893+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T04:44:33.904+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:44:33.905+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T05:01:33.945+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T05:01:33.947+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T05:29:34.033+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T05:29:34.035+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T05:42:34.564+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T05:42:34.566+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 2ms (3 connections now open to localhost:47018)
2017-12-06T05:43:34.565+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T05:56:34.106+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T05:56:34.108+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T06:10:34.145+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T06:10:34.147+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T07:14:34.314+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T07:14:34.316+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T07:19:04.326+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T07:19:04.328+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T18:08:08.173+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:08:08.175+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47018 due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.176+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-06T18:08:08.180+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-06T18:08:08.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47018
2017-12-06T18:08:08.201+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T18:08:08.202+0900 I REPL     [replication-16] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 529707 -- target:localhost:47018 db:local expDate:2017-12-06T08:06:04.849+0900 cmd:{ getMore: 37225257907, collection: "oplog.rs", maxTimeMS: 5000, term: 8, lastKnownCommittedOpTime: { ts: Timestamp 1512515099000|1, t: 8 } }. Last fetched optime (with hash): { ts: Timestamp 1512515099000|1, t: 8 }[1886086866381821185]. Restarts remaining: 3
2017-12-06T18:08:08.202+0900 I REPL     [replication-16] Scheduled new oplog query Fetcher source: localhost:47018 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515099000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 8, readConcern: { afterOpTime: { ts: Timestamp 1512515099000|1, t: 8 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 529728 -- target:localhost:47018 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515099000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 8, readConcern: { afterOpTime: { ts: Timestamp 1512515099000|1, t: 8 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-06T18:08:08.202+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47018
2017-12-06T18:08:08.208+0900 I REPL     [ReplicationExecutor] VoteRequester(term 8 dry run) received a yes vote from localhost:47017; response message: { term: 8, voteGranted: true, reason: "", ok: 1.0 }
2017-12-06T18:08:08.208+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-06T18:08:08.208+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host localhost:47018 due to bad connection status; 1 connections to that host remain open
2017-12-06T18:08:08.244+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512461342416615 microSec, clearing pool for localhost:47018 of 0 connections
2017-12-06T18:08:08.253+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: NotMaster: Not primary while running findAndModify command on collection config.lockpings
2017-12-06T18:08:08.257+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:47018(with timeout of 5 seconds)
2017-12-06T18:08:08.257+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:47018(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.257+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Marking host localhost:47018 as failed :: caused by :: HostUnreachable: network error while attempting to run command 'ismaster' on host 'localhost:47018' 
2017-12-06T18:08:08.257+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512455470045076 microSec, clearing pool for localhost:57041 of 0 connections
2017-12-06T18:08:08.257+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57041(with timeout of 5 seconds)
2017-12-06T18:08:08.257+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57041(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.258+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 56ms (2 connections now open to localhost:47018)
2017-12-06T18:08:08.258+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47018, took 57ms (2 connections now open to localhost:47018)
2017-12-06T18:08:08.258+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-06T18:08:08.258+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512373532309176 microSec, clearing pool for localhost:37018 of 0 connections
2017-12-06T18:08:08.258+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:37018(with timeout of 5 seconds)
2017-12-06T18:08:08.258+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:37018(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.258+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Marking host localhost:37018 as failed :: caused by :: HostUnreachable: network error while attempting to run command 'ismaster' on host 'localhost:37018' 
2017-12-06T18:08:08.259+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:08.260+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47018, took 59ms (1 connections now open to localhost:47018)
2017-12-06T18:08:08.261+0900 I REPL     [ReplicationExecutor] VoteRequester(term 9) received a no vote from localhost:47018 with reason "candidate's data is staler than mine"; response message: { term: 9, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-06T18:08:08.263+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s0
2017-12-06T18:08:08.270+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512457432542458 microSec, clearing pool for localhost:57018 of 0 connections
2017-12-06T18:08:08.270+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:57018(with timeout of 5 seconds)
2017-12-06T18:08:08.270+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:57018(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.270+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Marking host localhost:57018 as failed :: caused by :: HostUnreachable: network error while attempting to run command 'ismaster' on host 'localhost:57018' 
2017-12-06T18:08:08.265+0900 I REPL     [replication-16] Choosing new sync source because our current sync source, localhost:47018, has an OpTime ({ ts: Timestamp 1512551288000|1, t: 8 }) which is not ahead of ours ({ ts: Timestamp 1512551288000|1, t: 8 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-06T18:08:08.270+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s2
2017-12-06T18:08:08.270+0900 I REPL     [replication-16] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47018, OpTime { ts: Timestamp 1512551288000|1, t: 8 }, its sync source index:-1
2017-12-06T18:08:08.270+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47018 (config version: 1; last applied optime: { ts: Timestamp 1512551288000|1, t: 8 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-06T18:08:08.270+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-06T18:08:08.271+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-06T18:08:08.271+0900 I REPL     [ReplicationExecutor] Member localhost:47018 is now in state SECONDARY
2017-12-06T18:08:08.299+0900 I REPL     [ReplicationExecutor] VoteRequester(term 9) received a yes vote from localhost:47017; response message: { term: 9, voteGranted: true, reason: "", ok: 1.0 }
2017-12-06T18:08:08.299+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 9
2017-12-06T18:08:08.299+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-06T18:08:08.299+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-06T18:08:08.301+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-06T18:08:08.301+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-06T18:08:08.422+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 151ms (2 connections now open to localhost:47017)
2017-12-06T18:08:08.759+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-06T18:08:08.760+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:09.261+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:09.269+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-06T18:08:09.762+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:10.263+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:10.765+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:11.266+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:11.768+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:12.269+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:12.771+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:13.263+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47018: InvalidSyncSource: Sync source was cleared. Was localhost:47018
2017-12-06T18:08:13.273+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:13.774+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:14.181+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57952 #76 (16 connections now open)
2017-12-06T18:08:14.181+0900 I NETWORK  [conn76] received client metadata from 127.0.0.1:57952 conn76: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:14.193+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57954 #77 (17 connections now open)
2017-12-06T18:08:14.193+0900 I NETWORK  [conn77] received client metadata from 127.0.0.1:57954 conn77: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:14.276+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:14.278+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57956 #78 (18 connections now open)
2017-12-06T18:08:14.279+0900 I NETWORK  [conn78] received client metadata from 127.0.0.1:57956 conn78: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:14.281+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57958 #79 (19 connections now open)
2017-12-06T18:08:14.282+0900 I NETWORK  [conn79] received client metadata from 127.0.0.1:57958 conn79: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:14.777+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:15.279+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:15.780+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:16.281+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:16.782+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:17.283+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:17.783+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:18.284+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:18.786+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:19.287+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:19.789+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:24.269+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57990 #80 (20 connections now open)
2017-12-06T18:08:24.269+0900 I NETWORK  [conn80] received client metadata from 127.0.0.1:57990 conn80: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:38.260+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-06T18:08:38.271+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-06T18:08:38.275+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-06T18:09:08.259+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47018 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:09:08.301+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:10:36.280+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T18:10:36.282+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T18:37:04.594+0900 I COMMAND  [conn77] command local.oplog.rs command: getMore { getMore: 38537229703, collection: "oplog.rs", maxTimeMS: 5000, term: 9, lastKnownCommittedOpTime: { ts: Timestamp 1512553019000|1, t: 9 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512551288000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 9, readConcern: { afterOpTime: { ts: Timestamp 1512551288000|1, t: 8 } } } planSummary: COLLSCAN cursorid:38537229703 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 5266ms
2017-12-06T18:37:04.595+0900 I COMMAND  [conn79] command local.oplog.rs command: getMore { getMore: 35759553516, collection: "oplog.rs", maxTimeMS: 5000, term: 9, lastKnownCommittedOpTime: { ts: Timestamp 1512553019000|1, t: 9 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512551288000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 9, readConcern: { afterOpTime: { ts: Timestamp 1512551288000|1, t: 8 } } } planSummary: COLLSCAN cursorid:35759553516 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 5267ms
2017-12-06T19:06:06.838+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T19:06:06.841+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-06T19:11:36.853+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T19:11:36.854+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T19:18:06.868+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T19:18:06.870+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T19:33:36.910+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T19:33:36.914+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 5ms (1 connections now open to localhost:57042)
2017-12-06T20:20:37.035+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T20:20:37.036+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T20:40:04.557+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:59288 #81 (21 connections now open)
2017-12-06T20:40:04.558+0900 I NETWORK  [conn81] received client metadata from 127.0.0.1:59288 conn81: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T20:41:04.557+0900 I -        [conn77] end connection 127.0.0.1:57954 (21 connections now open)
2017-12-06T21:06:07.123+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T21:06:07.124+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-06T21:11:49.602+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60950 #82 (21 connections now open)
2017-12-06T21:11:49.602+0900 I NETWORK  [conn82] received client metadata from 127.0.0.1:60950 conn82: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T21:12:49.603+0900 I -        [conn79] end connection 127.0.0.1:57958 (21 connections now open)
2017-12-06T21:21:07.156+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T21:21:07.158+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-06T21:30:37.181+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T21:30:37.182+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T21:59:34.673+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33454 #83 (21 connections now open)
2017-12-06T21:59:34.673+0900 I NETWORK  [conn83] received client metadata from 127.0.0.1:33454 conn83: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T22:00:34.674+0900 I -        [conn81] end connection 127.0.0.1:59288 (21 connections now open)
2017-12-06T22:07:37.267+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T22:07:37.271+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-06T22:16:37.290+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T22:16:37.292+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-06T22:47:07.373+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T22:47:07.377+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-06T23:00:07.413+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T23:00:07.416+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-06T23:43:37.508+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T23:43:37.512+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-07T00:54:07.669+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T00:54:07.671+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T01:14:37.723+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T01:14:37.725+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-07T01:45:07.800+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T01:45:07.802+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T02:42:37.953+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T02:42:37.955+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-07T03:06:08.028+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T03:06:08.029+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-07T03:28:05.325+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36948 #84 (21 connections now open)
2017-12-07T03:28:05.326+0900 I NETWORK  [conn84] received client metadata from 127.0.0.1:36948 conn84: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T03:29:05.326+0900 I -        [conn78] end connection 127.0.0.1:57956 (21 connections now open)
2017-12-07T03:47:38.135+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T03:47:38.137+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T03:54:08.152+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T03:54:08.154+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T04:00:08.169+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T04:00:08.170+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-07T04:53:38.304+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T04:53:38.305+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-07T05:09:08.345+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T05:09:08.349+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-07T05:10:25.532+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37572 #85 (21 connections now open)
2017-12-07T05:10:25.532+0900 I NETWORK  [conn85] received client metadata from 127.0.0.1:37572 conn85: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T05:11:25.532+0900 I -        [conn76] end connection 127.0.0.1:57952 (21 connections now open)
2017-12-07T05:20:38.375+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T05:20:38.376+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-07T06:16:25.666+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37948 #86 (21 connections now open)
2017-12-07T06:16:25.669+0900 I NETWORK  [conn86] received client metadata from 127.0.0.1:37948 conn86: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T06:17:25.666+0900 I -        [conn84] end connection 127.0.0.1:36948 (21 connections now open)
2017-12-07T06:31:35.695+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38016 #87 (21 connections now open)
2017-12-07T06:31:35.696+0900 I NETWORK  [conn87] received client metadata from 127.0.0.1:38016 conn87: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T06:32:35.697+0900 I -        [conn83] end connection 127.0.0.1:33454 (21 connections now open)
2017-12-07T06:35:08.564+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T06:35:08.566+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-07T06:58:08.620+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T06:58:08.622+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-07T07:41:08.734+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T07:41:08.735+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-07T08:00:38.786+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T08:00:38.788+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
