2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9558 port=47018 dbpath=/data/shard1/rs1 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] options: { net: { port: 47018 }, processManagement: { fork: true }, replication: { replSet: "s1" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard1/rs1" }, systemLog: { destination: "file", path: "s1-r1.log" } }
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:46.050+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.052+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:46.079+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard1/rs1/diagnostic.data'
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:46.108+0900 I NETWORK  [thread1] waiting for connections on port 47018
2017-12-03T21:00:51.353+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43686 #1 (1 connection now open)
2017-12-03T21:00:51.354+0900 I -        [conn1] end connection 127.0.0.1:43686 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43690 #2 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:43690 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:51.355+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-03T21:00:51.356+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.357+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43704 #3 (2 connections now open)
2017-12-03T21:00:53.357+0900 I -        [conn3] end connection 127.0.0.1:43704 (2 connections now open)
2017-12-03T21:00:53.402+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:53.473+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43708 #4 (2 connections now open)
2017-12-03T21:00:53.473+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:43708 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:53.474+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-03T21:00:53.476+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 1ms (1 connections now open to localhost:47019)
2017-12-03T21:00:53.478+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s1", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:47017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:47018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:47019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e7737da32b8ce5ce759f') } }
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] This node is localhost:47018 in the config
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state STARTUP2
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] sync source candidate: localhost:47017
2017-12-03T21:00:53.515+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] creating replication oplog of size: 6116MB...
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:53.634+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.637+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.639+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.641+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (2 connections now open to localhost:47017)
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302451000|1 })
2017-12-03T21:00:53.646+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:53.646+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302451000|1, t: -1 }[2865188406503243212]
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302453478), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302451000|1, initialSyncOplogEnd: Timestamp 1512302451000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:53.654+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:53.655+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:53.656+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:00:53.656+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-03T21:01:03.657+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-03T21:01:08.659+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-03T21:01:08.659+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.661+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (1 connections now open to localhost:47019)
2017-12-03T21:01:08.662+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.663+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 1ms (2 connections now open to localhost:47019)
2017-12-03T21:02:10.737+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43882 #5 (3 connections now open)
2017-12-03T21:02:10.737+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:43882 conn5: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.833+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.834+0900 I COMMAND  [repl writer worker 2] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s1", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.835+0900 I NETWORK  [repl writer worker 7] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.836+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:47018:1512302530:4272451777790352026 (sleeping for 30000ms)
2017-12-03T21:02:10.837+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.838+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 6ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.844+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 5ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.850+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.851+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43954 #6 (4 connections now open)
2017-12-03T21:02:10.851+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:43954 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.854+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.856+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43958 #7 (5 connections now open)
2017-12-03T21:02:10.856+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:43958 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.856+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.880+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43964 #8 (6 connections now open)
2017-12-03T21:02:10.880+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:43964 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43970 #9 (7 connections now open)
2017-12-03T21:02:10.881+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:43970 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44024 #10 (8 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44026 #11 (9 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:44024 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.930+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:44026 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.015+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44048 #12 (10 connections now open)
2017-12-03T21:02:11.015+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:44048 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.202+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44064 #13 (11 connections now open)
2017-12-03T21:02:11.202+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:44064 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.452+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44096 #14 (12 connections now open)
2017-12-03T21:02:27.453+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:44096 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.609+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44114 #15 (13 connections now open)
2017-12-03T21:02:27.609+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:44114 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.676+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44140 #16 (14 connections now open)
2017-12-03T21:02:40.677+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:44140 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.679+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44146 #17 (15 connections now open)
2017-12-03T21:02:40.680+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:44146 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:02:40.847+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T21:02:40.848+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.849+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.852+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:03:10.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.848+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:03:10.850+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T21:09:40.866+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:09:40.867+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:55:10.958+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:55:10.960+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:03:40.979+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:03:40.982+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-03T22:41:11.077+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:41:11.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T23:17:41.152+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:17:41.154+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T23:32:11.188+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:32:11.190+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:06:41.267+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:06:41.268+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T00:25:41.311+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:25:41.313+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:30:11.323+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:30:11.324+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T00:42:41.356+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:42:41.358+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:53:11.383+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:53:11.384+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T01:03:09.904+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T01:03:09.906+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (3 connections now open to localhost:47019)
2017-12-04T01:04:09.905+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:25:41.467+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:25:41.469+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:46:41.520+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:46:41.524+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-04T01:59:11.555+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:59:11.556+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T02:04:41.568+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:04:41.570+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T02:20:11.606+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:20:11.607+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T02:35:11.644+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:35:11.646+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T03:10:11.733+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:10:11.734+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T04:23:41.920+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:23:41.922+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T04:40:11.962+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:40:11.964+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T05:21:12.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:21:12.080+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T05:56:42.169+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T05:56:42.171+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T06:51:42.314+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T06:51:42.315+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T07:26:12.406+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T07:26:12.408+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T07:28:42.413+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T07:28:42.415+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:41:54.169+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.176+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47019 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.185+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T15:41:54.180+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:41:54.180+0900 I REPL     [replication-2] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 126641 -- target:localhost:47019 db:local expDate:2017-12-04T08:14:55.761+0900 cmd:{ getMore: 34604852486, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342825000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342825000|1, t: 1 }[5334871594228210341]. Restarts remaining: 3
2017-12-04T15:41:54.185+0900 I REPL     [replication-2] Scheduled new oplog query Fetcher source: localhost:47019 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 126658 -- target:localhost:47019 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342825000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342825000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.185+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-04T15:41:54.185+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:41:54.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-04T15:41:54.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:47019; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.197+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:41:54.202+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47019 with reason "already voted for another candidate this term"; response message: { term: 2, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-04T15:41:54.205+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:47017 with reason "candidate's data is staler than mine"; response message: { term: 2, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-04T15:41:54.205+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-04T15:41:54.210+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 25ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.210+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 25ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.212+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 26ms (2 connections now open to localhost:47019)
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 26ms (2 connections now open to localhost:47017)
2017-12-04T15:41:54.212+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512342825000|1, t: 1 } is not greater than our last fetched OpTime { ts: Timestamp 1512342825000|1, t: 1 }. Choosing new sync source.
2017-12-04T15:41:54.212+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47017
2017-12-04T15:41:54.213+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T15:41:54.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 5ms (1 connections now open to localhost:47017)
2017-12-04T15:41:54.240+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47019: InvalidSyncSource: Sync source changed from localhost:47019 to localhost:47017
2017-12-04T15:41:54.242+0900 I REPL     [replication-0] Choosing new sync source because our current sync source, localhost:47017, has an OpTime ({ ts: Timestamp 1512369714000|1, t: 1 }) which is not ahead of ours ({ ts: Timestamp 1512369714000|1, t: 1 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T15:41:54.242+0900 I REPL     [replication-0] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47017, OpTime { ts: Timestamp 1512369714000|1, t: 1 }, its sync source index:-1
2017-12-04T15:41:54.242+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47017 (config version: 1; last applied optime: { ts: Timestamp 1512369714000|1, t: 1 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T15:41:54.242+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T15:41:54.242+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-04T15:41:54.250+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47017: InvalidSyncSource: Sync source was cleared. Was localhost:47017
2017-12-04T15:42:04.639+0900 I -        [conn4] end connection 127.0.0.1:43708 (15 connections now open)
2017-12-04T15:42:04.640+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:48070 #18 (15 connections now open)
2017-12-04T15:42:04.641+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:48070 conn18: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:09.243+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state PRIMARY
2017-12-04T15:42:09.245+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-04T15:42:10.465+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:42:10.466+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T15:42:10.837+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.839+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.840+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.842+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.844+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.845+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:10.847+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.848+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:24.213+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:24.216+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-04T15:42:54.202+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.205+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:57:11.239+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T15:57:11.243+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-04T16:12:11.267+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:12:11.269+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T16:45:25.216+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-04T16:45:25.268+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.268+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:30.218+0900 I REPL     [replication-0] Choosing new sync source because our current sync source, localhost:47019, has an OpTime ({ ts: Timestamp 1512372452000|1, t: 3 }) which is not ahead of ours ({ ts: Timestamp 1512372452000|1, t: 3 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T16:45:30.218+0900 I REPL     [replication-0] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:47019, OpTime { ts: Timestamp 1512372452000|1, t: 3 }, its sync source index:-1
2017-12-04T16:45:30.218+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47019 (config version: 1; last applied optime: { ts: Timestamp 1512372452000|1, t: 3 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T16:45:30.218+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T16:45:30.219+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47019: InvalidSyncSource: Sync source was cleared. Was localhost:47019
2017-12-04T16:45:31.892+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:45:31.894+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T16:45:32.303+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57019)
2017-12-04T16:45:32.305+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-04T16:45:32.306+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57041)
2017-12-04T16:45:32.308+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-04T16:45:32.309+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:37018)
2017-12-04T16:45:32.310+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-04T16:45:32.311+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:47019)
2017-12-04T16:45:32.313+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-04T16:45:32.314+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-04T16:45:35.790+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T16:45:35.790+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T16:45:35.791+0900 I REPL     [ReplicationExecutor] VoteRequester(term 3 dry run) received a yes vote from localhost:47017; response message: { term: 3, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T16:45:35.791+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] VoteRequester(term 4) received a yes vote from localhost:47017; response message: { term: 4, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 4
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-04T16:45:35.797+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-04T16:45:35.798+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-04T16:45:37.218+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-04T16:45:40.194+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37890 #19 (16 connections now open)
2017-12-04T16:45:40.195+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:37890 conn19: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.197+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37892 #20 (17 connections now open)
2017-12-04T16:45:40.197+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:37892 conn20: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.256+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37894 #21 (18 connections now open)
2017-12-04T16:45:40.256+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:37894 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:40.258+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37896 #22 (19 connections now open)
2017-12-04T16:45:40.259+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:37896 conn22: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:51.230+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38014 #23 (20 connections now open)
2017-12-04T16:45:51.231+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:38014 conn23: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:46:25.219+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T16:46:31.897+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:46:31.897+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 0ms (1 connections now open to localhost:57040)
2017-12-04T17:01:31.931+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T17:01:31.933+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T17:38:04.887+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36404 #24 (21 connections now open)
2017-12-04T17:38:04.888+0900 I NETWORK  [conn24] received client metadata from 127.0.0.1:36404 conn24: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:04.905+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36406 #25 (22 connections now open)
2017-12-04T17:38:04.905+0900 I NETWORK  [conn25] received client metadata from 127.0.0.1:36406 conn25: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:11.971+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36468 #26 (23 connections now open)
2017-12-04T17:38:11.972+0900 I NETWORK  [conn26] received client metadata from 127.0.0.1:36468 conn26: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:38:42.279+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36718 #27 (24 connections now open)
2017-12-04T17:38:42.280+0900 I NETWORK  [conn27] received client metadata from 127.0.0.1:36718 conn27: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:39:32.672+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37120 #28 (25 connections now open)
2017-12-04T17:39:32.672+0900 I NETWORK  [conn28] received client metadata from 127.0.0.1:37120 conn28: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:44:53.964+0900 I -        [conn26] end connection 127.0.0.1:36468 (25 connections now open)
2017-12-04T17:45:13.889+0900 I -        [conn27] end connection 127.0.0.1:36718 (24 connections now open)
2017-12-04T17:45:20.409+0900 I -        [conn28] end connection 127.0.0.1:37120 (23 connections now open)
2017-12-04T17:45:23.469+0900 I -        [conn25] end connection 127.0.0.1:36406 (22 connections now open)
2017-12-04T17:50:04.167+0900 I INDEX    [conn24] build index on: mongomart.item properties: { v: 2, key: { _fts: "text", _ftsx: 1 }, name: "title_text_slogan_text_description_text", ns: "mongomart.item", weights: { description: 1, slogan: 1, title: 1 }, default_language: "english", language_override: "language", textIndexVersion: 3 }
2017-12-04T17:50:04.168+0900 I INDEX    [conn24] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-04T17:50:04.177+0900 I INDEX    [conn24] build index done.  scanned 23 total records. 0 secs
2017-12-04T17:50:40.646+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42600 #29 (22 connections now open)
2017-12-04T17:50:40.646+0900 I NETWORK  [conn29] received client metadata from 127.0.0.1:42600 conn29: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:50:44.595+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42636 #30 (23 connections now open)
2017-12-04T17:50:44.595+0900 I NETWORK  [conn30] received client metadata from 127.0.0.1:42636 conn30: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:50:57.819+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:42742 #31 (24 connections now open)
2017-12-04T17:50:57.820+0900 I NETWORK  [conn31] received client metadata from 127.0.0.1:42742 conn31: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:51:42.106+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43096 #32 (25 connections now open)
2017-12-04T17:51:42.106+0900 I NETWORK  [conn32] received client metadata from 127.0.0.1:43096 conn32: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T17:58:00.280+0900 I -        [conn30] end connection 127.0.0.1:42636 (25 connections now open)
2017-12-04T17:58:50.698+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46612 #33 (25 connections now open)
2017-12-04T17:58:50.698+0900 I NETWORK  [conn33] received client metadata from 127.0.0.1:46612 conn33: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:02:33.071+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T18:02:33.072+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T18:03:45.708+0900 I -        [conn29] end connection 127.0.0.1:42600 (25 connections now open)
2017-12-04T18:03:50.699+0900 I -        [conn33] end connection 127.0.0.1:46612 (24 connections now open)
2017-12-04T18:04:20.686+0900 I -        [conn31] end connection 127.0.0.1:42742 (23 connections now open)
2017-12-04T18:04:29.801+0900 I -        [conn32] end connection 127.0.0.1:43096 (22 connections now open)
2017-12-04T18:05:02.174+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49616 #34 (22 connections now open)
2017-12-04T18:05:02.174+0900 I NETWORK  [conn34] received client metadata from 127.0.0.1:49616 conn34: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:05:26.692+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49810 #35 (23 connections now open)
2017-12-04T18:05:26.692+0900 I NETWORK  [conn35] received client metadata from 127.0.0.1:49810 conn35: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:06:12.899+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50186 #36 (24 connections now open)
2017-12-04T18:06:12.900+0900 I NETWORK  [conn36] received client metadata from 127.0.0.1:50186 conn36: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:07:33.605+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50860 #37 (25 connections now open)
2017-12-04T18:07:33.606+0900 I NETWORK  [conn37] received client metadata from 127.0.0.1:50860 conn37: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:11:12.902+0900 I -        [conn36] end connection 127.0.0.1:50186 (25 connections now open)
2017-12-04T18:12:28.823+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:53290 #38 (25 connections now open)
2017-12-04T18:12:28.823+0900 I NETWORK  [conn38] received client metadata from 127.0.0.1:53290 conn38: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:12:41.227+0900 I -        [conn35] end connection 127.0.0.1:49810 (25 connections now open)
2017-12-04T18:16:03.403+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:55086 #39 (25 connections now open)
2017-12-04T18:16:03.403+0900 I NETWORK  [conn39] received client metadata from 127.0.0.1:55086 conn39: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:27:35.272+0900 I -        [conn34] end connection 127.0.0.1:49616 (25 connections now open)
2017-12-04T18:27:50.878+0900 I -        [conn39] end connection 127.0.0.1:55086 (24 connections now open)
2017-12-04T18:27:57.952+0900 I -        [conn38] end connection 127.0.0.1:53290 (23 connections now open)
2017-12-04T18:28:04.414+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60928 #40 (23 connections now open)
2017-12-04T18:28:04.415+0900 I NETWORK  [conn40] received client metadata from 127.0.0.1:60928 conn40: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:04.433+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60930 #41 (24 connections now open)
2017-12-04T18:28:04.434+0900 I NETWORK  [conn41] received client metadata from 127.0.0.1:60930 conn41: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:13.294+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32776 #42 (25 connections now open)
2017-12-04T18:28:13.295+0900 I NETWORK  [conn42] received client metadata from 127.0.0.1:32776 conn42: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:28:13.307+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32778 #43 (26 connections now open)
2017-12-04T18:28:13.307+0900 I NETWORK  [conn43] received client metadata from 127.0.0.1:32778 conn43: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:33:28.578+0900 I -        [conn37] end connection 127.0.0.1:50860 (26 connections now open)
2017-12-04T18:33:28.579+0900 I -        [conn40] end connection 127.0.0.1:60928 (25 connections now open)
2017-12-04T18:34:06.443+0900 I -        [conn41] end connection 127.0.0.1:60930 (24 connections now open)
2017-12-04T18:34:06.446+0900 I -        [conn43] end connection 127.0.0.1:32778 (23 connections now open)
2017-12-04T18:52:42.444+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44728 #44 (23 connections now open)
2017-12-04T18:52:42.444+0900 I NETWORK  [conn44] received client metadata from 127.0.0.1:44728 conn44: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T18:53:42.444+0900 I -        [conn22] end connection 127.0.0.1:37896 (23 connections now open)
2017-12-04T19:13:57.177+0900 I REPL     [ReplicationExecutor] can't see a majority of the set, relinquishing primary
2017-12-04T19:13:57.177+0900 I REPL     [ReplicationExecutor] Stepping down from primary in response to heartbeat
2017-12-04T19:13:57.177+0900 I COMMAND  [conn21] command local.oplog.rs command: getMore { getMore: 36122414565, collection: "oplog.rs", maxTimeMS: 5000, term: 4, lastKnownCommittedOpTime: { ts: Timestamp 1512382297000|1, t: 4 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512372452000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 4, readConcern: { afterOpTime: { ts: Timestamp 1512372452000|1, t: 3 } } } planSummary: COLLSCAN cursorid:36122414565 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 139700ms
2017-12-04T19:13:57.178+0900 I COMMAND  [conn20] command local.oplog.rs command: getMore { getMore: 37293789345, collection: "oplog.rs", maxTimeMS: 5000, term: 4, lastKnownCommittedOpTime: { ts: Timestamp 1512382297000|1, t: 4 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512372452000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 4, readConcern: { afterOpTime: { ts: Timestamp 1512372452000|1, t: 3 } } } planSummary: COLLSCAN cursorid:37293789345 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 139700ms
2017-12-04T19:13:57.179+0900 I REPL     [replExecDBWorker-0] transition to SECONDARY
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 44
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 23
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 21
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 20
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 19
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 18
2017-12-04T19:13:57.179+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 2
2017-12-04T19:13:57.179+0900 I -        [conn5] end connection 127.0.0.1:43882 (22 connections now open)
2017-12-04T19:13:57.179+0900 I -        [conn15] end connection 127.0.0.1:44114 (22 connections now open)
2017-12-04T19:13:57.179+0900 I -        [conn12] end connection 127.0.0.1:44048 (22 connections now open)
2017-12-04T19:13:57.180+0900 I -        [conn42] end connection 127.0.0.1:32776 (20 connections now open)
2017-12-04T19:13:57.180+0900 I -        [conn14] end connection 127.0.0.1:44096 (19 connections now open)
2017-12-04T19:13:57.180+0900 I -        [conn8] end connection 127.0.0.1:43964 (18 connections now open)
2017-12-04T19:13:57.181+0900 I -        [conn13] end connection 127.0.0.1:44064 (17 connections now open)
2017-12-04T19:13:57.179+0900 I -        [conn10] end connection 127.0.0.1:44024 (22 connections now open)
2017-12-04T19:13:57.182+0900 I -        [conn16] end connection 127.0.0.1:44140 (15 connections now open)
2017-12-04T19:13:57.179+0900 I -        [conn6] end connection 127.0.0.1:43954 (22 connections now open)
2017-12-04T19:13:57.182+0900 I -        [conn9] end connection 127.0.0.1:43970 (12 connections now open)
2017-12-04T19:13:57.182+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-04T19:13:57.182+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-04T19:13:57.182+0900 I -        [conn24] end connection 127.0.0.1:36404 (11 connections now open)
2017-12-04T19:13:57.182+0900 I -        [conn17] end connection 127.0.0.1:44146 (10 connections now open)
2017-12-04T19:13:57.183+0900 I -        [conn11] end connection 127.0.0.1:44026 (9 connections now open)
2017-12-04T19:13:57.184+0900 I -        [conn7] end connection 127.0.0.1:43958 (8 connections now open)
2017-12-04T19:13:57.244+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T19:13:57.244+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T19:13:59.688+0900 I -        [conn44] end connection 127.0.0.1:44728 (7 connections now open)
2017-12-04T19:14:07.571+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54018 #45 (7 connections now open)
2017-12-04T19:14:07.571+0900 I NETWORK  [conn45] received client metadata from 127.0.0.1:54018 conn45: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:07.674+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54026 #46 (8 connections now open)
2017-12-04T19:14:07.674+0900 I NETWORK  [conn46] received client metadata from 127.0.0.1:54026 conn46: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:08.082+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54034 #47 (9 connections now open)
2017-12-04T19:14:08.082+0900 I NETWORK  [conn47] received client metadata from 127.0.0.1:54034 conn47: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:12.184+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-04T19:14:13.180+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47017
2017-12-04T19:14:13.180+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T19:14:13.181+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-04T19:14:13.182+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T19:14:13.183+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (2 connections now open to localhost:47017)
2017-12-04T19:14:20.595+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54176 #48 (10 connections now open)
2017-12-04T19:14:20.595+0900 I NETWORK  [conn48] received client metadata from 127.0.0.1:54176 conn48: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.604+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54186 #49 (11 connections now open)
2017-12-04T19:14:20.604+0900 I NETWORK  [conn49] received client metadata from 127.0.0.1:54186 conn49: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.608+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54190 #50 (12 connections now open)
2017-12-04T19:14:20.608+0900 I NETWORK  [conn50] received client metadata from 127.0.0.1:54190 conn50: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.615+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54200 #51 (13 connections now open)
2017-12-04T19:14:20.616+0900 I NETWORK  [conn51] received client metadata from 127.0.0.1:54200 conn51: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.924+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:57042)
2017-12-04T19:14:20.926+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-04T19:14:20.928+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:57017)
2017-12-04T19:14:20.929+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T19:14:20.931+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54216 #52 (14 connections now open)
2017-12-04T19:14:20.931+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:37017)
2017-12-04T19:14:20.933+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T19:14:20.934+0900 I NETWORK  [conn52] received client metadata from 127.0.0.1:54216 conn52: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.935+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:47018)
2017-12-04T19:14:20.935+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54222 #53 (15 connections now open)
2017-12-04T19:14:20.936+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54224 #54 (16 connections now open)
2017-12-04T19:14:20.936+0900 I NETWORK  [conn53] received client metadata from 127.0.0.1:54222 conn53: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.936+0900 I NETWORK  [conn54] received client metadata from 127.0.0.1:54224 conn54: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.936+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-04T19:14:20.946+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54232 #55 (17 connections now open)
2017-12-04T19:14:20.946+0900 I NETWORK  [conn55] received client metadata from 127.0.0.1:54232 conn55: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.947+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54236 #56 (18 connections now open)
2017-12-04T19:14:20.947+0900 I NETWORK  [conn56] received client metadata from 127.0.0.1:54236 conn56: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.949+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:54242 #57 (19 connections now open)
2017-12-04T19:14:20.949+0900 I NETWORK  [conn57] received client metadata from 127.0.0.1:54242 conn57: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:27.245+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T19:14:27.247+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T19:14:57.251+0900 I -        [conn19] end connection 127.0.0.1:37890 (19 connections now open)
2017-12-04T19:16:35.081+0900 I -        [conn23] end connection 127.0.0.1:38014 (18 connections now open)
2017-12-04T19:18:57.239+0900 I -        [conn21] end connection 127.0.0.1:37894 (17 connections now open)
2017-12-04T19:19:02.200+0900 I -        [conn20] end connection 127.0.0.1:37892 (16 connections now open)
2017-12-04T19:28:50.483+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T19:28:50.485+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T19:35:20.501+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T19:35:20.502+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T20:27:51.317+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T20:27:51.321+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-04T21:44:51.501+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:44:51.503+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T22:20:21.595+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T22:20:21.599+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 5ms (1 connections now open to localhost:57040)
2017-12-04T22:31:51.624+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T22:31:51.627+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-04T22:55:54.639+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-04T22:55:54.640+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 1ms (3 connections now open to localhost:47017)
2017-12-04T22:56:54.640+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T23:02:51.700+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T23:02:51.702+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T23:25:21.759+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T23:25:21.761+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T23:44:21.809+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T23:44:21.811+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T00:03:21.860+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:03:21.864+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T00:40:21.950+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T00:40:21.953+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-05T00:51:21.976+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:51:21.977+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:26:22.058+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T01:26:22.059+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T01:33:52.072+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:33:52.074+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T01:46:52.098+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T01:46:52.100+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T01:56:52.120+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:56:52.122+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T02:59:22.272+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:59:22.276+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-05T03:31:52.348+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:31:52.349+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T03:34:22.354+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T03:34:22.355+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T04:06:52.434+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T04:06:52.435+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T04:34:22.503+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:34:22.504+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T04:57:22.561+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:57:22.562+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T05:16:22.610+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:16:22.611+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:15:22.732+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T06:15:22.733+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:53:52.807+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T06:53:52.809+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T07:44:52.916+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T07:44:52.917+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T07:46:52.923+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T07:46:52.923+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-05T07:51:52.936+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T07:51:52.937+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T15:30:53.179+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:30:53.179+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.183+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60154 #58 (16 connections now open)
2017-12-05T15:30:53.183+0900 I NETWORK  [conn58] received client metadata from 127.0.0.1:60154 conn58: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:53.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:37019)
2017-12-05T15:30:53.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:47017)
2017-12-05T15:30:53.219+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:57017)
2017-12-05T15:30:53.219+0900 I REPL     [replication-0] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 308641 -- target:localhost:47017 db:local expDate:2017-12-05T08:05:35.644+0900 cmd:{ getMore: 17418435668, collection: "oplog.rs", maxTimeMS: 5000, term: 5, lastKnownCommittedOpTime: { ts: Timestamp 1512428670000|1, t: 5 } }. Last fetched optime (with hash): { ts: Timestamp 1512428670000|1, t: 5 }[-3228870133416877210]. Restarts remaining: 3
2017-12-05T15:30:53.219+0900 I REPL     [replication-0] Scheduled new oplog query Fetcher source: localhost:47017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 6, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 308656 -- target:localhost:47017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 6, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 5 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-05T15:30:53.220+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T15:30:53.220+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-05T15:30:53.243+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state PRIMARY
2017-12-05T15:30:53.246+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-05T15:30:53.246+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 27ms (2 connections now open to localhost:47017)
2017-12-05T15:30:53.246+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 27ms (2 connections now open to localhost:47017)
2017-12-05T15:30:53.249+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512428670000|1, t: 5 } is not greater than our last fetched OpTime { ts: Timestamp 1512428670000|1, t: 5 }. Choosing new sync source.
2017-12-05T15:30:53.249+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-05T15:30:53.253+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: NotMaster: Not primary while running findAndModify command on collection config.lockpings
2017-12-05T15:30:53.266+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512373532306671 microSec, clearing pool for localhost:57041 of 0 connections
2017-12-05T15:30:53.279+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57041(with timeout of 5 seconds)
2017-12-05T15:30:53.279+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57041(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.283+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T15:30:53.783+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-05T15:30:53.784+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T15:30:58.247+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47017: InvalidSyncSource: Sync source was cleared. Was localhost:47017
2017-12-05T15:30:58.251+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-05T15:30:58.251+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-05T15:30:58.252+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 1ms (1 connections now open to localhost:47019)
2017-12-05T15:30:58.254+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-05T15:30:58.256+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (2 connections now open to localhost:47019)
2017-12-05T15:31:10.044+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T15:31:10.048+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-05T15:31:10.051+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-05T15:31:53.184+0900 I -        [conn18] end connection 127.0.0.1:48070 (16 connections now open)
2017-12-05T15:31:53.247+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:32:39.233+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T15:32:39.234+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T16:03:27.184+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T16:03:27.184+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T16:03:27.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-05T16:03:27.187+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-05T16:03:27.205+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 21ms (2 connections now open to localhost:47017)
2017-12-05T16:03:27.207+0900 I REPL     [ReplicationExecutor] VoteRequester(term 6 dry run) received a yes vote from localhost:47017; response message: { term: 6, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T16:03:27.207+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T16:03:27.209+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-05T16:03:27.211+0900 I REPL     [ReplicationExecutor] VoteRequester(term 7) received a yes vote from localhost:47017; response message: { term: 7, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T16:03:27.211+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 7
2017-12-05T16:03:27.211+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-05T16:03:27.211+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-05T16:03:27.211+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-05T16:03:27.211+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host localhost:47019 due to bad connection status; 3 connections to that host remain open
2017-12-05T16:03:27.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:37017)
2017-12-05T16:03:27.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:47019)
2017-12-05T16:03:27.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:57018)
2017-12-05T16:03:27.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:57040)
2017-12-05T16:03:27.238+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:47019 (config version: 1; last applied optime: { ts: Timestamp 1512455885000|1, t: 6 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-05T16:03:27.249+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 40ms (3 connections now open to localhost:47019)
2017-12-05T16:03:27.249+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 38ms (3 connections now open to localhost:47019)
2017-12-05T16:03:27.249+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 65ms (3 connections now open to localhost:47019)
2017-12-05T16:03:27.249+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-05T16:03:27.249+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-05T16:03:27.249+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-05T16:03:27.258+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: NotMaster: not master
2017-12-05T16:03:27.259+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-05T16:03:27.260+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:27.668+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:03:27.668+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:47019: InvalidSyncSource: Sync source was cleared. Was localhost:47019
2017-12-05T16:03:27.761+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:29.188+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-05T16:03:32.231+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:35800 #59 (16 connections now open)
2017-12-05T16:03:32.232+0900 I NETWORK  [conn59] received client metadata from 127.0.0.1:35800 conn59: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:32.235+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:35802 #60 (17 connections now open)
2017-12-05T16:03:32.235+0900 I NETWORK  [conn60] received client metadata from 127.0.0.1:35802 conn60: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:49.273+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:35984 #61 (18 connections now open)
2017-12-05T16:03:49.274+0900 I NETWORK  [conn61] received client metadata from 127.0.0.1:35984 conn61: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.539+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-05T16:03:52.542+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-05T16:03:52.545+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-05T16:04:27.205+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:04:27.249+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T16:04:27.249+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:47019 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:04:46.202+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36510 #62 (19 connections now open)
2017-12-05T16:04:46.203+0900 I NETWORK  [conn62] received client metadata from 127.0.0.1:36510 conn62: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:04:54.506+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:36578 #63 (20 connections now open)
2017-12-05T16:04:54.507+0900 I NETWORK  [conn63] received client metadata from 127.0.0.1:36578 conn63: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:05:23.012+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-05T16:05:23.014+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-05T16:05:59.203+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:37106 #64 (21 connections now open)
2017-12-05T16:05:59.203+0900 I NETWORK  [conn64] received client metadata from 127.0.0.1:37106 conn64: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:06:59.203+0900 I -        [conn59] end connection 127.0.0.1:35800 (21 connections now open)
2017-12-05T16:07:59.527+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38118 #65 (21 connections now open)
2017-12-05T16:07:59.527+0900 I NETWORK  [conn65] received client metadata from 127.0.0.1:38118 conn65: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:07:59.545+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38120 #66 (22 connections now open)
2017-12-05T16:07:59.545+0900 I NETWORK  [conn66] received client metadata from 127.0.0.1:38120 conn66: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:08:01.526+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38142 #67 (23 connections now open)
2017-12-05T16:08:01.527+0900 I NETWORK  [conn67] received client metadata from 127.0.0.1:38142 conn67: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:08:56.158+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38604 #68 (24 connections now open)
2017-12-05T16:08:56.159+0900 I NETWORK  [conn68] received client metadata from 127.0.0.1:38604 conn68: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:13:44.774+0900 I -        [conn63] end connection 127.0.0.1:36578 (24 connections now open)
2017-12-05T16:13:57.881+0900 I -        [conn67] end connection 127.0.0.1:38142 (23 connections now open)
2017-12-05T16:17:46.253+0900 I -        [conn65] end connection 127.0.0.1:38118 (22 connections now open)
2017-12-05T16:17:47.372+0900 I -        [conn66] end connection 127.0.0.1:38120 (21 connections now open)
2017-12-05T16:18:40.688+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43394 #69 (21 connections now open)
2017-12-05T16:18:40.689+0900 I NETWORK  [conn69] received client metadata from 127.0.0.1:43394 conn69: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-3", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:19:07.407+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43626 #70 (22 connections now open)
2017-12-05T16:19:07.407+0900 I NETWORK  [conn70] received client metadata from 127.0.0.1:43626 conn70: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-0", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:19:13.799+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43692 #71 (23 connections now open)
2017-12-05T16:19:13.800+0900 I NETWORK  [conn71] received client metadata from 127.0.0.1:43692 conn71: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-1", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:19:16.300+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43712 #72 (24 connections now open)
2017-12-05T16:19:16.301+0900 I NETWORK  [conn72] received client metadata from 127.0.0.1:43712 conn72: { driver: { name: "NetworkInterfaceASIO-TaskExecutorPool-2", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
