2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9558 port=47018 dbpath=/data/shard1/rs1 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:45.948+0900 I CONTROL  [initandlisten] options: { net: { port: 47018 }, processManagement: { fork: true }, replication: { replSet: "s1" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard1/rs1" }, systemLog: { destination: "file", path: "s1-r1.log" } }
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:45.970+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:46.050+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:46.051+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:46.052+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:46.079+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard1/rs1/diagnostic.data'
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:46.107+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:46.108+0900 I NETWORK  [thread1] waiting for connections on port 47018
2017-12-03T21:00:51.353+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43686 #1 (1 connection now open)
2017-12-03T21:00:51.354+0900 I -        [conn1] end connection 127.0.0.1:43686 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43690 #2 (1 connection now open)
2017-12-03T21:00:51.354+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:43690 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:51.355+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47017
2017-12-03T21:00:51.356+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47017, took 1ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.357+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43704 #3 (2 connections now open)
2017-12-03T21:00:53.357+0900 I -        [conn3] end connection 127.0.0.1:43704 (2 connections now open)
2017-12-03T21:00:53.402+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:53.473+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43708 #4 (2 connections now open)
2017-12-03T21:00:53.473+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:43708 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:53.474+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:47019
2017-12-03T21:00:53.476+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:47019, took 1ms (1 connections now open to localhost:47019)
2017-12-03T21:00:53.478+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s1", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:47017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:47018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:47019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e7737da32b8ce5ce759f') } }
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] This node is localhost:47018 in the config
2017-12-03T21:00:53.478+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state SECONDARY
2017-12-03T21:00:53.479+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state STARTUP2
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] sync source candidate: localhost:47017
2017-12-03T21:00:53.515+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.515+0900 I REPL     [replication-0] creating replication oplog of size: 6116MB...
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:53.534+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:53.634+0900 I REPL     [replication-0] ******
2017-12-03T21:00:53.635+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.637+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (1 connections now open to localhost:47017)
2017-12-03T21:00:53.639+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47017
2017-12-03T21:00:53.641+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47017, took 2ms (2 connections now open to localhost:47017)
2017-12-03T21:00:53.645+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302451000|1 })
2017-12-03T21:00:53.646+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:47017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:53.646+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302451000|1, t: -1 }[2865188406503243212]
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:53.647+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302453478), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302451000|1, initialSyncOplogEnd: Timestamp 1512302451000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:53.654+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:53.654+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:53.655+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:53.656+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:00:53.656+0900 I REPL     [ReplicationExecutor] Member localhost:47019 is now in state SECONDARY
2017-12-03T21:01:03.657+0900 I REPL     [ReplicationExecutor] Member localhost:47017 is now in state PRIMARY
2017-12-03T21:01:08.659+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:47019
2017-12-03T21:01:08.659+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.661+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 2ms (1 connections now open to localhost:47019)
2017-12-03T21:01:08.662+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:47019
2017-12-03T21:01:08.663+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:47019, took 1ms (2 connections now open to localhost:47019)
2017-12-03T21:02:10.737+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43882 #5 (3 connections now open)
2017-12-03T21:02:10.737+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:43882 conn5: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.832+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.833+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.834+0900 I COMMAND  [repl writer worker 2] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s1", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.834+0900 I SHARDING [repl writer worker 7] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.835+0900 I NETWORK  [repl writer worker 7] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.836+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:47018:1512302530:4272451777790352026 (sleeping for 30000ms)
2017-12-03T21:02:10.837+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.837+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.838+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.843+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 6ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.844+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 5ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.845+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.850+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.851+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43954 #6 (4 connections now open)
2017-12-03T21:02:10.851+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:43954 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.854+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.856+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43958 #7 (5 connections now open)
2017-12-03T21:02:10.856+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:43958 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.856+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.880+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43964 #8 (6 connections now open)
2017-12-03T21:02:10.880+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:43964 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:10.881+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43970 #9 (7 connections now open)
2017-12-03T21:02:10.881+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:43970 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44024 #10 (8 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44026 #11 (9 connections now open)
2017-12-03T21:02:10.930+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:44024 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.930+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:44026 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.015+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44048 #12 (10 connections now open)
2017-12-03T21:02:11.015+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:44048 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.202+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44064 #13 (11 connections now open)
2017-12-03T21:02:11.202+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:44064 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.452+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44096 #14 (12 connections now open)
2017-12-03T21:02:27.453+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:44096 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.609+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44114 #15 (13 connections now open)
2017-12-03T21:02:27.609+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:44114 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.676+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44140 #16 (14 connections now open)
2017-12-03T21:02:40.677+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:44140 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.679+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:44146 #17 (15 connections now open)
2017-12-03T21:02:40.680+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:44146 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:02:40.847+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T21:02:40.848+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.849+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.852+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.855+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:03:10.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.848+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:03:10.850+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T21:09:40.866+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:09:40.867+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:55:10.958+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:55:10.960+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:03:40.979+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:03:40.982+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-03T22:41:11.077+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:41:11.078+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
