2017-12-03T21:00:51.826+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9825 port=57019 dbpath=/data/shard2/rs2 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:51.827+0900 I CONTROL  [initandlisten] options: { net: { port: 57019 }, processManagement: { fork: true }, replication: { replSet: "s2" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard2/rs2" }, systemLog: { destination: "file", path: "s2-r2.log" } }
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:51.848+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:51.926+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.927+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:51.948+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard2/rs2/diagnostic.data'
2017-12-03T21:00:51.972+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:51.972+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:51.972+0900 I NETWORK  [thread1] waiting for connections on port 57019
2017-12-03T21:00:57.026+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51750 #1 (1 connection now open)
2017-12-03T21:00:57.026+0900 I -        [conn1] end connection 127.0.0.1:51750 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51754 #2 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:51754 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:57.027+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-03T21:00:57.028+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 1ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51794 #3 (2 connections now open)
2017-12-03T21:00:59.031+0900 I -        [conn3] end connection 127.0.0.1:51794 (2 connections now open)
2017-12-03T21:00:59.072+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:59.137+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51796 #4 (2 connections now open)
2017-12-03T21:00:59.137+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:51796 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:59.138+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-03T21:00:59.139+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 1ms (1 connections now open to localhost:57018)
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s2", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:57017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:57018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:57019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e77974cc47503351a376') } }
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] This node is localhost:57019 in the config
2017-12-03T21:00:59.142+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:59.143+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:59.143+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-03T21:00:59.143+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state STARTUP2
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] sync source candidate: localhost:57017
2017-12-03T21:00:59.178+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.178+0900 I REPL     [replication-0] creating replication oplog of size: 6071MB...
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:59.196+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:59.273+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.274+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.276+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.277+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.279+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-03T21:00:59.280+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302457000|1 })
2017-12-03T21:00:59.281+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302457000|1, t: -1 }[3144501803686678102]
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Initial sync attempt finishing up.
2017-12-03T21:00:59.282+0900 I REPL     [replication-1] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302459142), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302457000|1, initialSyncOplogEnd: Timestamp 1512302457000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:59.292+0900 I REPL     [replication-1] initial sync done; took 0s.
2017-12-03T21:00:59.292+0900 I REPL     [replication-1] Starting replication fetcher thread
2017-12-03T21:00:59.293+0900 I REPL     [replication-1] Starting replication applier thread
2017-12-03T21:00:59.293+0900 I REPL     [replication-1] Starting replication reporter thread
2017-12-03T21:00:59.293+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:59.293+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:59.294+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state SECONDARY
2017-12-03T21:00:59.294+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:01:09.296+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-03T21:01:10.296+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-03T21:01:10.299+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:01:10.299+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 0ms (2 connections now open to localhost:57017)
2017-12-03T21:02:10.834+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51958 #5 (3 connections now open)
2017-12-03T21:02:10.834+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:51958 conn5: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.913+0900 I INDEX    [repl writer worker 1] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.913+0900 I INDEX    [repl writer worker 1] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.914+0900 I INDEX    [repl writer worker 1] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.915+0900 I COMMAND  [repl writer worker 3] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 10] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s2", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 10] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.923+0900 I NETWORK  [repl writer worker 10] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.923+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:57019:1512302530:-5824242036816374222 (sleeping for 30000ms)
2017-12-03T21:02:10.924+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.939+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.947+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.951+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52060 #6 (4 connections now open)
2017-12-03T21:02:10.951+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:52060 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.977+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.991+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.992+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.992+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:11.017+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:11.206+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52098 #7 (5 connections now open)
2017-12-03T21:02:11.206+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:52098 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.453+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52122 #8 (6 connections now open)
2017-12-03T21:02:27.453+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:52122 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.609+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52140 #9 (7 connections now open)
2017-12-03T21:02:27.610+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:52140 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.684+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52180 #10 (8 connections now open)
2017-12-03T21:02:40.684+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:52180 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.685+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52184 #11 (9 connections now open)
2017-12-03T21:02:40.686+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:52184 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.829+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52192 #12 (10 connections now open)
2017-12-03T21:02:40.830+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:52192 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.834+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52198 #13 (11 connections now open)
2017-12-03T21:02:40.835+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:52198 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.854+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52206 #14 (12 connections now open)
2017-12-03T21:02:40.854+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:52206 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.928+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:02:40.929+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:02:40.930+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.932+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.933+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52226 #15 (13 connections now open)
2017-12-03T21:02:40.934+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.934+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:52226 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.935+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52228 #16 (14 connections now open)
2017-12-03T21:02:40.935+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:52228 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.936+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:02:40.939+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52232 #17 (15 connections now open)
2017-12-03T21:02:40.940+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:52232 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:03:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:03:10.930+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:03:10.931+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T21:53:41.053+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:53:41.054+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:12:41.088+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:12:41.089+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:17:41.097+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:17:41.098+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:27:41.125+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:27:41.127+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T22:51:44.320+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T22:51:44.322+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-03T22:52:44.321+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:09:11.221+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:09:11.223+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T23:18:41.245+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:18:41.248+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-03T23:27:34.389+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T23:27:34.391+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-03T23:28:34.390+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T23:29:11.271+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:29:11.272+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T23:44:41.305+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T23:44:41.307+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T00:17:41.393+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T00:17:41.395+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T01:15:09.590+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T01:15:09.591+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T01:16:09.591+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T01:47:11.611+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:47:11.615+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-04T01:54:41.630+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T01:54:41.632+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T02:10:11.671+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T02:10:11.672+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T02:24:41.707+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T02:24:41.708+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T02:43:41.752+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:43:41.754+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T03:59:41.939+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:59:41.941+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T04:03:14.919+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T04:03:14.921+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-04T04:04:14.920+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:07:11.959+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T04:07:11.961+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T04:23:11.999+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:23:12.011+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 12ms (1 connections now open to localhost:57041)
2017-12-04T04:37:12.046+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T04:37:12.047+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T05:45:42.216+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:45:42.217+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T06:25:05.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T06:25:05.219+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T06:26:05.217+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T06:31:42.345+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T06:31:42.347+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T07:44:12.528+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T07:44:12.530+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:41:54.182+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.185+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T15:41:54.191+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-04T15:41:54.191+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-04T15:41:54.191+0900 I REPL     [replication-0] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 134604 -- target:localhost:57017 db:local expDate:2017-12-04T08:14:55.440+0900 cmd:{ getMore: 21465883049, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342830000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342830000|1, t: 1 }[2855280599495995645]. Restarts remaining: 3
2017-12-04T15:41:54.192+0900 I REPL     [replication-0] Scheduled new oplog query Fetcher source: localhost:57017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 134623 -- target:localhost:57017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 1, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.192+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.195+0900 I REPL     [ReplicationExecutor] VoteRequester(term 1 dry run) received a yes vote from localhost:57018; response message: { term: 1, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.195+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T15:41:54.199+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a no vote from localhost:57017 with reason "candidate's data is staler than mine"; response message: { term: 2, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-04T15:41:54.200+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2) received a yes vote from localhost:57018; response message: { term: 2, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 2
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-04T15:41:54.201+0900 I REPL     [ReplicationExecutor] Heartbeats updated catchup target optime to { ts: Timestamp 1512369714000|1, t: 1 }
2017-12-04T15:41:54.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 21ms (2 connections now open to localhost:57018)
2017-12-04T15:41:54.212+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.212+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.214+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 22ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.214+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 23ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.221+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 30ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.230+0900 I REPL     [rsSync] Caught up to the latest known optime successfully after becoming primary.
2017-12-04T15:41:54.230+0900 I REPL     [rsSync] Exited primary catch-up mode.
2017-12-04T15:41:54.233+0900 I REPL     [rsBackgroundSync] Replication producer stopped after oplog fetcher finished returning a batch from our sync source.  Abandoning this batch of oplog entries and re-evaluating our sync source.
2017-12-04T15:41:55.231+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-04T15:41:57.183+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56062 #18 (16 connections now open)
2017-12-04T15:41:57.183+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:56062 conn18: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:57.186+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56064 #19 (17 connections now open)
2017-12-04T15:41:57.187+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:56064 conn19: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:59.227+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-04T15:41:59.232+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56090 #20 (18 connections now open)
2017-12-04T15:41:59.232+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:56090 conn20: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:59.233+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56092 #21 (19 connections now open)
2017-12-04T15:41:59.233+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:56092 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:07.244+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56102 #22 (20 connections now open)
2017-12-04T15:42:07.245+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:56102 conn22: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:42:10.544+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:10.546+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T15:42:10.871+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.872+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.874+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.875+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.876+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.878+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:10.879+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:54.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:42:54.227+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:44:40.551+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:44:40.553+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T15:58:30.263+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:59260 #23 (21 connections now open)
2017-12-04T15:58:30.266+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:59260 conn23: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:59:30.264+0900 I -        [conn18] end connection 127.0.0.1:56062 (21 connections now open)
2017-12-04T16:45:25.186+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:47019)
2017-12-04T16:45:25.191+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45638 #24 (21 connections now open)
2017-12-04T16:45:25.191+0900 I NETWORK  [conn24] received client metadata from 127.0.0.1:45638 conn24: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:25.199+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45646 #25 (22 connections now open)
2017-12-04T16:45:25.201+0900 I REPL     [conn2] stepping down from primary, because a new term has begun: 3
2017-12-04T16:45:25.201+0900 I REPL     [replExecDBWorker-2] transition to SECONDARY
2017-12-04T16:45:25.201+0900 I NETWORK  [conn25] received client metadata from 127.0.0.1:45646 conn25: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:25.201+0900 I NETWORK  [replExecDBWorker-2] legacy transport layer closing all connections
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 25
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 24
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 23
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 22
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 21
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 20
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 19
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 4
2017-12-04T16:45:25.202+0900 I NETWORK  [replExecDBWorker-2] Skip closing connection for connection # 2
2017-12-04T16:45:25.202+0900 I -        [conn15] end connection 127.0.0.1:52226 (22 connections now open)
2017-12-04T16:45:25.202+0900 I -        [conn14] end connection 127.0.0.1:52206 (21 connections now open)
2017-12-04T16:45:25.203+0900 I -        [conn11] end connection 127.0.0.1:52184 (20 connections now open)
2017-12-04T16:45:25.203+0900 I -        [conn13] end connection 127.0.0.1:52198 (19 connections now open)
2017-12-04T16:45:25.203+0900 I -        [conn7] end connection 127.0.0.1:52098 (18 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn16] end connection 127.0.0.1:52228 (17 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn9] end connection 127.0.0.1:52140 (16 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn12] end connection 127.0.0.1:52192 (15 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn8] end connection 127.0.0.1:52122 (14 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn17] end connection 127.0.0.1:52232 (13 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn10] end connection 127.0.0.1:52180 (12 connections now open)
2017-12-04T16:45:25.204+0900 I -        [conn5] end connection 127.0.0.1:51958 (11 connections now open)
2017-12-04T16:45:25.205+0900 I -        [conn6] end connection 127.0.0.1:52060 (10 connections now open)
2017-12-04T16:45:25.228+0900 I COMMAND  [conn20] command local.oplog.rs command: getMore { getMore: 38454106792, collection: "oplog.rs", maxTimeMS: 5000, term: 2, lastKnownCommittedOpTime: { ts: Timestamp 1512372445000|1, t: 2 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 2, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:38454106792 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 15739 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1074917ms
2017-12-04T16:45:25.228+0900 I COMMAND  [conn19] command local.oplog.rs command: getMore { getMore: 35231716431, collection: "oplog.rs", maxTimeMS: 5000, term: 2, lastKnownCommittedOpTime: { ts: Timestamp 1512372445000|1, t: 2 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512369714000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 2, readConcern: { afterOpTime: { ts: Timestamp 1512369714000|1, t: 1 } } } planSummary: COLLSCAN cursorid:35231716431 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 16267 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1074917ms
2017-12-04T16:45:25.267+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.267+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.904+0900 I -        [conn23] end connection 127.0.0.1:59260 (9 connections now open)
2017-12-04T16:45:25.905+0900 I -        [conn21] end connection 127.0.0.1:56092 (8 connections now open)
2017-12-04T16:45:30.216+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-04T16:45:31.188+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-04T16:45:31.188+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T16:45:31.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (1 connections now open to localhost:57017)
2017-12-04T16:45:31.194+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T16:45:31.195+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (2 connections now open to localhost:57017)
2017-12-04T16:45:31.204+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45734 #26 (8 connections now open)
2017-12-04T16:45:31.204+0900 I NETWORK  [conn26] received client metadata from 127.0.0.1:45734 conn26: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:31.972+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:45:31.974+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T16:45:32.019+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45772 #27 (9 connections now open)
2017-12-04T16:45:32.020+0900 I NETWORK  [conn27] received client metadata from 127.0.0.1:45772 conn27: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.029+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45786 #28 (10 connections now open)
2017-12-04T16:45:32.029+0900 I NETWORK  [conn28] received client metadata from 127.0.0.1:45786 conn28: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45794 #29 (11 connections now open)
2017-12-04T16:45:32.030+0900 I NETWORK  [conn29] received client metadata from 127.0.0.1:45794 conn29: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.031+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45796 #30 (12 connections now open)
2017-12-04T16:45:32.032+0900 I NETWORK  [conn30] received client metadata from 127.0.0.1:45796 conn30: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.303+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45806 #31 (13 connections now open)
2017-12-04T16:45:32.303+0900 I NETWORK  [conn31] received client metadata from 127.0.0.1:45806 conn31: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.303+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45808 #32 (14 connections now open)
2017-12-04T16:45:32.304+0900 I NETWORK  [conn32] received client metadata from 127.0.0.1:45808 conn32: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.306+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45814 #33 (15 connections now open)
2017-12-04T16:45:32.306+0900 I NETWORK  [conn33] received client metadata from 127.0.0.1:45814 conn33: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.330+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57019)
2017-12-04T16:45:32.330+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45832 #34 (16 connections now open)
2017-12-04T16:45:32.331+0900 I NETWORK  [conn34] received client metadata from 127.0.0.1:45832 conn34: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.331+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-04T16:45:32.333+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57041)
2017-12-04T16:45:32.334+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-04T16:45:32.336+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:37018)
2017-12-04T16:45:32.336+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45844 #35 (17 connections now open)
2017-12-04T16:45:32.338+0900 I NETWORK  [conn35] received client metadata from 127.0.0.1:45844 conn35: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.338+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-04T16:45:32.339+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45846 #36 (18 connections now open)
2017-12-04T16:45:32.339+0900 I NETWORK  [conn36] received client metadata from 127.0.0.1:45846 conn36: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:32.342+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-04T16:45:32.343+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-04T16:45:48.935+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46002 #37 (19 connections now open)
2017-12-04T16:45:48.936+0900 I NETWORK  [conn37] received client metadata from 127.0.0.1:46002 conn37: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:49.061+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46008 #38 (20 connections now open)
2017-12-04T16:45:49.062+0900 I NETWORK  [conn38] received client metadata from 127.0.0.1:46008 conn38: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:49.457+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:46022 #39 (21 connections now open)
2017-12-04T16:45:49.458+0900 I NETWORK  [conn39] received client metadata from 127.0.0.1:46022 conn39: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:55.271+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:45:55.279+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 9ms (1 connections now open to localhost:57042)
2017-12-04T16:46:25.191+0900 I -        [conn24] end connection 127.0.0.1:45638 (21 connections now open)
2017-12-04T16:46:25.213+0900 I -        [conn25] end connection 127.0.0.1:45646 (20 connections now open)
2017-12-04T16:50:25.230+0900 I -        [conn19] end connection 127.0.0.1:56064 (19 connections now open)
2017-12-04T16:50:25.230+0900 I -        [conn20] end connection 127.0.0.1:56090 (18 connections now open)
2017-12-04T16:50:25.254+0900 I -        [conn22] end connection 127.0.0.1:56102 (17 connections now open)
2017-12-04T16:50:41.226+0900 I -        [conn26] end connection 127.0.0.1:45734 (16 connections now open)
2017-12-04T17:34:33.070+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T17:34:33.072+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T17:44:27.289+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T17:44:27.290+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T17:45:27.289+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T17:54:33.112+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T17:54:33.114+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T17:56:52.309+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T17:56:52.310+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-04T17:57:52.310+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T18:17:33.165+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T18:17:33.167+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T19:13:57.199+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: NotMaster: not master
2017-12-04T19:13:57.199+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512302530923547 microSec, clearing pool for localhost:57042 of 0 connections
2017-12-04T19:13:57.200+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57042(with timeout of 5 seconds)
2017-12-04T19:13:57.200+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57042(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-04T19:13:57.200+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:57.211+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-04T19:13:57.214+0900 I REPL     [replication-5] Choosing new sync source because our current sync source, localhost:57017, has an OpTime ({ ts: Timestamp 1512382437000|1, t: 3 }) which is not ahead of ours ({ ts: Timestamp 1512382437000|1, t: 3 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T19:13:57.235+0900 I REPL     [replication-5] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57017, OpTime { ts: Timestamp 1512382437000|1, t: 3 }, its sync source index:-1
2017-12-04T19:13:57.235+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57017 (config version: 1; last applied optime: { ts: Timestamp 1512382437000|1, t: 3 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T19:13:57.235+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T19:13:57.702+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-04T19:13:57.703+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:58.204+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:58.706+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:59.207+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:59.652+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T19:13:59.709+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:00.211+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:00.713+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:01.214+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:01.716+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:02.217+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:02.240+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-04T19:14:02.719+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:03.221+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:03.723+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:04.225+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:04.727+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:05.228+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:05.730+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:06.232+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:06.734+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:07.236+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:07.738+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:08.240+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:08.741+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:14:12.238+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-04T19:14:12.239+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57018
2017-12-04T19:14:12.239+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-04T19:14:12.241+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (1 connections now open to localhost:57018)
2017-12-04T19:14:12.243+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-04T19:14:12.245+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 1ms (2 connections now open to localhost:57018)
2017-12-04T19:14:20.944+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:57017)
2017-12-04T19:14:20.945+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T19:14:20.946+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:37017)
2017-12-04T19:14:20.948+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T19:14:20.949+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:47018)
2017-12-04T19:14:20.950+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-04T19:34:20.548+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T19:34:20.550+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T19:46:20.580+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T19:46:20.582+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-04T20:01:51.301+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T20:01:51.303+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T20:30:51.373+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T20:30:51.378+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 5ms (1 connections now open to localhost:57042)
2017-12-04T21:04:51.452+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T21:04:51.457+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 5ms (1 connections now open to localhost:57042)
2017-12-04T21:20:54.401+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-04T21:20:54.403+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-04T21:21:54.402+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T21:49:51.565+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:49:51.567+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T22:14:21.624+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T22:14:21.624+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-04T22:23:21.648+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T22:23:21.649+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T22:44:51.698+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T22:44:51.699+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T23:07:51.757+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T23:07:51.758+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T23:53:51.873+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T23:53:51.877+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T00:00:21.893+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T00:00:21.928+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 35ms (1 connections now open to localhost:57042)
2017-12-05T00:24:51.984+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:24:51.986+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T00:33:52.032+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:33:52.033+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:35:22.159+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T01:35:22.161+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T01:45:52.183+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:45:52.185+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T02:36:22.299+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T02:36:22.301+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T02:52:22.337+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:52:22.339+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T03:12:52.390+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:12:52.391+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T03:17:52.403+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T03:17:52.404+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T03:36:05.098+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T03:36:05.100+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-05T03:37:05.099+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T03:38:25.102+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T03:38:25.104+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-05T03:39:25.104+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T04:09:22.529+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:09:22.530+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T05:04:52.660+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:04:52.661+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T05:12:52.677+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:12:52.678+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T05:33:22.715+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T05:33:22.719+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T05:52:52.763+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:52:52.764+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T15:30:53.186+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:39952 #40 (16 connections now open)
2017-12-05T15:30:53.186+0900 I NETWORK  [conn40] received client metadata from 127.0.0.1:39952 conn40: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:53.194+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:30:53.195+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57018 due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.195+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T15:30:53.195+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T15:30:53.196+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-05T15:30:53.196+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-05T15:30:53.197+0900 I REPL     [ReplicationExecutor] VoteRequester(term 4 dry run) received a yes vote from localhost:57017; response message: { term: 4, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T15:30:53.197+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T15:30:53.197+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-05T15:30:53.197+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 2ms (2 connections now open to localhost:57018)
2017-12-05T15:30:53.220+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:37019)
2017-12-05T15:30:53.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:47017)
2017-12-05T15:30:53.223+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:57017)
2017-12-05T15:30:53.220+0900 I REPL     [replication-6] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 314696 -- target:localhost:57018 db:local expDate:2017-12-05T08:05:35.580+0900 cmd:{ getMore: 36306519948, collection: "oplog.rs", maxTimeMS: 5000, term: 4, lastKnownCommittedOpTime: { ts: Timestamp 1512428660000|1, t: 4 } }. Last fetched optime (with hash): { ts: Timestamp 1512428670000|1, t: 4 }[-4572138473438295509]. Restarts remaining: 3
2017-12-05T15:30:53.223+0900 I REPL     [replication-6] Scheduled new oplog query Fetcher source: localhost:57018 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 314727 -- target:localhost:57018 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-05T15:30:53.220+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T15:30:53.226+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T15:30:53.221+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5) received a no vote from localhost:57018 with reason "already voted for another candidate this term"; response message: { term: 5, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-05T15:30:53.227+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5) received a no vote from localhost:57017 with reason "already voted for another candidate this term"; response message: { term: 5, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-05T15:30:53.227+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-05T15:30:53.229+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 6ms (2 connections now open to localhost:57018)
2017-12-05T15:30:53.229+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 9ms (2 connections now open to localhost:57018)
2017-12-05T15:30:53.244+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512428670000|1, t: 4 } is not greater than our last fetched OpTime { ts: Timestamp 1512428670000|1, t: 4 }. Choosing new sync source.
2017-12-05T15:30:53.244+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-05T15:30:53.245+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-05T15:30:53.245+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state PRIMARY
2017-12-05T15:30:53.265+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: NotMaster: Not primary while running findAndModify command on collection config.lockpings
2017-12-05T15:30:53.266+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512373532333581 microSec, clearing pool for localhost:57041 of 0 connections
2017-12-05T15:30:53.279+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57041(with timeout of 5 seconds)
2017-12-05T15:30:53.279+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57041(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.282+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T15:30:53.783+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-05T15:30:53.783+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T15:30:58.232+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57018: InvalidSyncSource: Sync source was cleared. Was localhost:57018
2017-12-05T15:30:59.246+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57018
2017-12-05T15:31:09.308+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T15:31:09.309+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T15:31:09.977+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T15:31:09.981+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-05T15:31:09.984+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-05T15:31:53.197+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.198+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.204+0900 I -        [conn40] end connection 127.0.0.1:39952 (16 connections now open)
2017-12-05T16:03:27.190+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43710 #41 (16 connections now open)
2017-12-05T16:03:27.197+0900 I NETWORK  [conn41] received client metadata from 127.0.0.1:43710 conn41: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.199+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T16:03:27.199+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T16:03:27.199+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-05T16:03:27.199+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-05T16:03:27.208+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 9ms (2 connections now open to localhost:57017)
2017-12-05T16:03:27.208+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 9ms (2 connections now open to localhost:57018)
2017-12-05T16:03:27.208+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5 dry run) received a no vote from localhost:57017 with reason "candidate's term is lower than mine"; response message: { term: 6, voteGranted: false, reason: "candidate's term is lower than mine", ok: 1.0 }
2017-12-05T16:03:27.208+0900 I REPL     [ReplicationExecutor] not running for primary, we have been superceded already
2017-12-05T16:03:27.208+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending connection to host localhost:57018 due to bad connection status; 1 connections to that host remain open
2017-12-05T16:03:27.226+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:37017)
2017-12-05T16:03:27.226+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:47019)
2017-12-05T16:03:27.226+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1518 secs, remote host 127.0.0.1:57018)
2017-12-05T16:03:27.226+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:57040)
2017-12-05T16:03:27.229+0900 I REPL     [replication-5] Choosing new sync source because our current sync source, localhost:57018, has an OpTime ({ ts: Timestamp 1512455885000|1, t: 5 }) which is not ahead of ours ({ ts: Timestamp 1512455885000|1, t: 5 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-05T16:03:27.229+0900 I REPL     [replication-5] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57018, OpTime { ts: Timestamp 1512455885000|1, t: 5 }, its sync source index:-1
2017-12-05T16:03:27.230+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57018 (config version: 1; last applied optime: { ts: Timestamp 1512455885000|1, t: 5 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-05T16:03:27.230+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-05T16:03:27.234+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state SECONDARY
2017-12-05T16:03:27.234+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-05T16:03:27.257+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: NotMaster: not master
2017-12-05T16:03:27.259+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-05T16:03:27.260+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:27.674+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:03:27.674+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57018: InvalidSyncSource: Sync source was cleared. Was localhost:57018
2017-12-05T16:03:27.761+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:33.232+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57018
2017-12-05T16:03:33.233+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T16:03:33.235+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (2 connections now open to localhost:57018)
2017-12-05T16:03:52.486+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-05T16:03:52.490+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-05T16:03:52.492+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-05T16:04:21.801+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-05T16:04:21.803+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-05T16:04:27.198+0900 I -        [conn41] end connection 127.0.0.1:43710 (16 connections now open)
2017-12-05T16:04:27.208+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:26:23.132+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T16:26:23.134+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T17:08:56.217+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 2373 secs, remote host 127.0.0.1:57017)
2017-12-05T17:08:56.217+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 2373 secs, remote host 127.0.0.1:57042)
2017-12-05T17:08:56.219+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-05T17:08:56.225+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: NotMaster: not master
2017-12-05T17:08:56.229+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-05T17:08:56.230+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:08:56.733+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:08:57.235+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T17:09:01.220+0900 I REPL     [replication-8] Choosing new sync source because our current sync source, localhost:57018, has an OpTime ({ ts: Timestamp 1512461336000|1, t: 6 }) which is not ahead of ours ({ ts: Timestamp 1512461336000|1, t: 6 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-05T17:09:01.220+0900 I REPL     [replication-8] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57018, OpTime { ts: Timestamp 1512461336000|1, t: 6 }, its sync source index:-1
2017-12-05T17:09:01.221+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57018 (config version: 1; last applied optime: { ts: Timestamp 1512461336000|1, t: 6 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-05T17:09:01.221+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-05T17:09:01.231+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57018: InvalidSyncSource: Sync source was cleared. Was localhost:57018
2017-12-05T17:09:01.656+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:09:01.658+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T17:09:02.362+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T17:09:02.363+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s2
2017-12-05T17:09:02.364+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 6 secs, remote host 127.0.0.1:47018)
2017-12-05T17:09:02.365+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-05T17:09:02.366+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-05T17:09:11.223+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state PRIMARY
2017-12-05T17:09:11.224+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57018
2017-12-05T17:19:01.679+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T17:19:01.681+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T17:25:58.245+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T17:25:58.247+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-05T17:26:58.246+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T17:55:13.304+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T17:55:13.306+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-05T17:56:13.304+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T18:13:02.432+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T18:13:02.432+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-05T18:19:32.448+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T18:19:32.449+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T18:40:32.494+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-05T18:40:32.495+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (2 connections now open to localhost:57041)
2017-12-05T18:41:32.497+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57041 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T19:01:02.549+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T19:01:02.550+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T19:30:33.453+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T19:30:33.457+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 4ms (3 connections now open to localhost:57018)
2017-12-05T19:31:33.456+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T19:34:32.636+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T19:34:32.637+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T19:54:02.685+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T19:54:02.687+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T20:36:32.785+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T20:36:32.789+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T21:22:02.894+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T21:22:02.896+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T21:31:43.655+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T21:31:43.656+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 1ms (3 connections now open to localhost:57018)
2017-12-05T21:32:43.655+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T21:35:13.659+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-05T21:35:13.662+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 3ms (3 connections now open to localhost:57018)
2017-12-05T21:36:53.658+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T21:37:32.941+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T21:37:32.942+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T21:53:32.980+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T21:53:32.981+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T21:59:32.992+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T21:59:32.995+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-05T22:19:03.063+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T22:19:03.066+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-05T22:31:03.090+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T22:31:03.091+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T22:52:33.141+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T22:52:33.143+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T23:17:33.203+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T23:17:33.204+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T23:26:33.226+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T23:26:33.228+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T00:29:03.379+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T00:29:03.380+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T01:19:03.503+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T01:19:03.505+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T01:43:03.568+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T01:43:03.572+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-06T01:52:33.595+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T01:52:33.597+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T02:06:03.632+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T02:06:03.633+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T02:42:03.722+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T02:42:03.724+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T02:56:33.759+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T02:56:33.761+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-06T03:13:03.802+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T03:13:03.803+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T03:16:03.811+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T03:16:03.812+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T03:35:33.864+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T03:35:33.868+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-06T04:25:03.989+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T04:25:03.991+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T04:40:34.044+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T04:40:34.046+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T04:57:04.085+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T04:57:04.086+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T05:11:04.121+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T05:11:04.123+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T05:28:04.165+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T05:28:04.169+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-06T05:34:04.184+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T05:34:04.186+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T06:50:34.363+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T06:50:34.366+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 3ms (1 connections now open to localhost:57040)
2017-12-06T06:55:04.709+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-06T06:55:04.713+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 5ms (3 connections now open to localhost:57018)
2017-12-06T06:56:04.709+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T07:20:34.430+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T07:20:34.432+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T07:26:54.773+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-06T07:26:54.775+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 2ms (3 connections now open to localhost:57018)
2017-12-06T07:27:54.774+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 2 connections to that host remain open
2017-12-06T07:32:34.460+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-06T07:32:34.461+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-06T18:08:08.179+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:08:08.190+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57018 due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.189+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-06T18:08:08.190+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-06T18:08:08.199+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-06T18:08:08.199+0900 I REPL     [replication-12] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 500746 -- target:localhost:57018 db:local expDate:2017-12-06T08:06:04.850+0900 cmd:{ getMore: 34992069717, collection: "oplog.rs", maxTimeMS: 5000, term: 7, lastKnownCommittedOpTime: { ts: Timestamp 1512515099000|1, t: 7 } }. Last fetched optime (with hash): { ts: Timestamp 1512515099000|1, t: 7 }[-2473850676848592113]. Restarts remaining: 3
2017-12-06T18:08:08.200+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57018
2017-12-06T18:08:08.201+0900 I REPL     [replication-12] Scheduled new oplog query Fetcher source: localhost:57018 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515099000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 7, readConcern: { afterOpTime: { ts: Timestamp 1512515099000|1, t: 7 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 500768 -- target:localhost:57018 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515099000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 7, readConcern: { afterOpTime: { ts: Timestamp 1512515099000|1, t: 7 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-06T18:08:08.203+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-06T18:08:08.203+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57018
2017-12-06T18:08:08.206+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 7ms (2 connections now open to localhost:57017)
2017-12-06T18:08:08.210+0900 I REPL     [ReplicationExecutor] VoteRequester(term 7 dry run) received a yes vote from localhost:57017; response message: { term: 7, voteGranted: true, reason: "", ok: 1.0 }
2017-12-06T18:08:08.210+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-06T18:08:08.216+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 16ms (2 connections now open to localhost:57018)
2017-12-06T18:08:08.216+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57018, took 17ms (2 connections now open to localhost:57018)
2017-12-06T18:08:08.217+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57018, took 18ms (2 connections now open to localhost:57018)
2017-12-06T18:08:08.239+0900 I REPL     [ReplicationExecutor] VoteRequester(term 8) received a no vote from localhost:57017 with reason "already voted for another candidate this term"; response message: { term: 8, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-06T18:08:08.244+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512455453782802 microSec, clearing pool for localhost:57041 of 0 connections
2017-12-06T18:08:08.253+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: NotMaster: Not primary while running findAndModify command on collection config.lockpings
2017-12-06T18:08:08.256+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:57041(with timeout of 5 seconds)
2017-12-06T18:08:08.256+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:57041(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.258+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:08.259+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512461342364546 microSec, clearing pool for localhost:47018 of 0 connections
2017-12-06T18:08:08.259+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:47018(with timeout of 5 seconds)
2017-12-06T18:08:08.259+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:47018(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.259+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Marking host localhost:47018 as failed :: caused by :: HostUnreachable: network error while attempting to run command 'ismaster' on host 'localhost:47018' 
2017-12-06T18:08:08.259+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-06T18:08:08.261+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Detected bad connection created at 1512373532336482 microSec, clearing pool for localhost:37018 of 0 connections
2017-12-06T18:08:08.261+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Dropping all pooled connections to localhost:37018(with timeout of 5 seconds)
2017-12-06T18:08:08.261+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Ending connection to host localhost:37018(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-06T18:08:08.261+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Marking host localhost:37018 as failed :: caused by :: HostUnreachable: network error while attempting to run command 'ismaster' on host 'localhost:37018' 
2017-12-06T18:08:08.260+0900 I REPL     [ReplicationExecutor] VoteRequester(term 8) received a no vote from localhost:57018 with reason "candidate's data is staler than mine"; response message: { term: 7, voteGranted: false, reason: "candidate's data is staler than mine", ok: 1.0 }
2017-12-06T18:08:08.261+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-06T18:08:08.262+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s0
2017-12-06T18:08:08.263+0900 I REPL     [replication-12] Choosing new sync source because our current sync source, localhost:57018, has an OpTime ({ ts: Timestamp 1512515104000|1, t: 7 }) which is not ahead of ours ({ ts: Timestamp 1512515104000|1, t: 7 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-06T18:08:08.266+0900 I REPL     [replication-12] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57018, OpTime { ts: Timestamp 1512515104000|1, t: 7 }, its sync source index:-1
2017-12-06T18:08:08.266+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57018 (config version: 1; last applied optime: { ts: Timestamp 1512515104000|1, t: 7 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-06T18:08:08.266+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-06T18:08:08.267+0900 I REPL     [ReplicationExecutor] Member localhost:57018 is now in state SECONDARY
2017-12-06T18:08:08.283+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57018: InvalidSyncSource: Sync source was cleared. Was localhost:57018
2017-12-06T18:08:08.759+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-06T18:08:08.760+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:09.261+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:09.762+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:10.264+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:10.765+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:11.266+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:11.768+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:12.269+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:12.771+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:13.273+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:13.774+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:14.276+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:14.777+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:15.279+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:15.780+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:16.281+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:16.782+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:17.283+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:17.784+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:18.228+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-06T18:08:18.228+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-06T18:08:18.229+0900 I REPL     [ReplicationExecutor] VoteRequester(term 8 dry run) received a yes vote from localhost:57017; response message: { term: 8, voteGranted: true, reason: "", ok: 1.0 }
2017-12-06T18:08:18.229+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-06T18:08:18.232+0900 I REPL     [ReplicationExecutor] VoteRequester(term 9) received a yes vote from localhost:57018; response message: { term: 9, voteGranted: true, reason: "", ok: 1.0 }
2017-12-06T18:08:18.232+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 9
2017-12-06T18:08:18.232+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-06T18:08:18.232+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-06T18:08:18.233+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-06T18:08:18.233+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-06T18:08:18.284+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:18.786+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:19.263+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-06T18:08:19.287+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:19.788+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-06T18:08:21.183+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43474 #42 (16 connections now open)
2017-12-06T18:08:21.184+0900 I NETWORK  [conn42] received client metadata from 127.0.0.1:43474 conn42: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:21.188+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43476 #43 (17 connections now open)
2017-12-06T18:08:21.189+0900 I NETWORK  [conn43] received client metadata from 127.0.0.1:43476 conn43: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:23.271+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43478 #44 (18 connections now open)
2017-12-06T18:08:23.271+0900 I NETWORK  [conn44] received client metadata from 127.0.0.1:43478 conn44: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:23.272+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43480 #45 (19 connections now open)
2017-12-06T18:08:23.272+0900 I NETWORK  [conn45] received client metadata from 127.0.0.1:43480 conn45: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:08:38.207+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 30 secs, remote host 127.0.0.1:57018)
2017-12-06T18:08:38.208+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-06T18:08:38.261+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-06T18:08:38.263+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-06T18:08:44.293+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:43710 #46 (20 connections now open)
2017-12-06T18:08:44.293+0900 I NETWORK  [conn46] received client metadata from 127.0.0.1:43710 conn46: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T18:09:08.206+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:09:08.213+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:09:08.218+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57018 because the pool meets constraints; 1 connections to that host remain open
2017-12-06T18:09:36.386+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T18:09:36.388+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T18:37:04.595+0900 I COMMAND  [conn43] command local.oplog.rs command: getMore { getMore: 36411430927, collection: "oplog.rs", maxTimeMS: 5000, term: 9, lastKnownCommittedOpTime: { ts: Timestamp 1512553019000|1, t: 9 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515104000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 9, readConcern: { afterOpTime: { ts: Timestamp 1512515104000|1, t: 7 } } } planSummary: COLLSCAN cursorid:36411430927 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 5270ms
2017-12-06T18:37:04.595+0900 I COMMAND  [conn44] command local.oplog.rs command: getMore { getMore: 35296578814, collection: "oplog.rs", maxTimeMS: 5000, term: 9, lastKnownCommittedOpTime: { ts: Timestamp 1512553019000|1, t: 9 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512515104000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 9, readConcern: { afterOpTime: { ts: Timestamp 1512515104000|1, t: 7 } } } planSummary: COLLSCAN cursorid:35296578814 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 5270ms
2017-12-06T19:54:59.478+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50874 #47 (21 connections now open)
2017-12-06T19:54:59.479+0900 I NETWORK  [conn47] received client metadata from 127.0.0.1:50874 conn47: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T19:55:59.477+0900 I -        [conn42] end connection 127.0.0.1:43474 (21 connections now open)
2017-12-06T20:01:37.110+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T20:01:37.111+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T20:14:29.505+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:60492 #48 (21 connections now open)
2017-12-06T20:14:29.505+0900 I NETWORK  [conn48] received client metadata from 127.0.0.1:60492 conn48: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T20:15:29.505+0900 I -        [conn43] end connection 127.0.0.1:43476 (21 connections now open)
2017-12-06T20:16:07.145+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T20:16:07.147+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T20:26:49.526+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:38300 #49 (21 connections now open)
2017-12-06T20:26:49.526+0900 I NETWORK  [conn49] received client metadata from 127.0.0.1:38300 conn49: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T20:27:49.526+0900 I -        [conn45] end connection 127.0.0.1:43480 (21 connections now open)
2017-12-06T20:32:07.179+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T20:32:07.181+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T20:39:07.195+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T20:39:07.195+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 0ms (1 connections now open to localhost:57041)
2017-12-06T20:48:07.214+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T20:48:07.215+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-06T21:31:07.312+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T21:31:07.315+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-06T22:11:37.403+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T22:11:37.407+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-06T22:23:37.434+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T22:23:37.435+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-06T22:33:37.458+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T22:33:37.462+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-06T22:38:54.766+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:47786 #50 (21 connections now open)
2017-12-06T22:38:54.766+0900 I NETWORK  [conn50] received client metadata from 127.0.0.1:47786 conn50: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-06T22:39:54.766+0900 I -        [conn47] end connection 127.0.0.1:50874 (21 connections now open)
2017-12-06T23:02:07.519+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T23:02:07.522+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 3ms (1 connections now open to localhost:57041)
2017-12-06T23:23:07.572+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-06T23:23:07.574+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-06T23:35:07.603+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T23:35:07.605+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T23:47:07.633+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T23:47:07.635+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T23:56:07.656+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-06T23:56:07.658+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-06T23:59:44.918+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:48894 #51 (21 connections now open)
2017-12-06T23:59:44.918+0900 I NETWORK  [conn51] received client metadata from 127.0.0.1:48894 conn51: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T00:00:44.918+0900 I -        [conn50] end connection 127.0.0.1:47786 (21 connections now open)
2017-12-07T00:19:07.708+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T00:19:07.709+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T00:19:49.952+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49076 #52 (21 connections now open)
2017-12-07T00:19:49.953+0900 I NETWORK  [conn52] received client metadata from 127.0.0.1:49076 conn52: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T00:20:49.952+0900 I -        [conn44] end connection 127.0.0.1:43478 (21 connections now open)
2017-12-07T00:36:07.748+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T00:36:07.750+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T00:49:37.783+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T00:49:37.784+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T00:59:45.044+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49512 #53 (21 connections now open)
2017-12-07T00:59:45.044+0900 I NETWORK  [conn53] received client metadata from 127.0.0.1:49512 conn53: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T01:00:45.044+0900 I -        [conn48] end connection 127.0.0.1:60492 (21 connections now open)
2017-12-07T01:11:15.064+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:49594 #54 (21 connections now open)
2017-12-07T01:11:15.064+0900 I NETWORK  [conn54] received client metadata from 127.0.0.1:49594 conn54: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T01:12:15.064+0900 I -        [conn51] end connection 127.0.0.1:48894 (21 connections now open)
2017-12-07T01:33:37.894+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T01:33:37.896+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-07T01:45:37.928+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T01:45:37.929+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T01:51:37.944+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T01:51:37.945+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T02:01:37.969+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T02:01:37.971+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T02:06:07.981+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T02:06:07.982+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T02:23:00.191+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:50174 #55 (21 connections now open)
2017-12-07T02:23:00.192+0900 I NETWORK  [conn55] received client metadata from 127.0.0.1:50174 conn55: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T02:24:00.192+0900 I -        [conn49] end connection 127.0.0.1:38300 (21 connections now open)
2017-12-07T02:43:08.088+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T02:43:08.090+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T03:50:08.258+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T03:50:08.262+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 4ms (1 connections now open to localhost:57041)
2017-12-07T04:10:38.309+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T04:10:38.311+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T04:32:35.456+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51128 #56 (21 connections now open)
2017-12-07T04:32:35.456+0900 I NETWORK  [conn56] received client metadata from 127.0.0.1:51128 conn56: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T04:34:35.456+0900 I -        [conn54] end connection 127.0.0.1:49594 (21 connections now open)
2017-12-07T04:35:45.459+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51150 #57 (21 connections now open)
2017-12-07T04:35:45.459+0900 I NETWORK  [conn57] received client metadata from 127.0.0.1:51150 conn57: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T04:36:45.459+0900 I -        [conn53] end connection 127.0.0.1:49512 (21 connections now open)
2017-12-07T05:59:08.576+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-07T05:59:08.577+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-07T06:03:38.586+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T06:03:38.588+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-07T06:50:38.708+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-07T06:50:38.713+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 5ms (1 connections now open to localhost:57042)
2017-12-07T07:03:55.763+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51916 #58 (21 connections now open)
2017-12-07T07:03:55.764+0900 I NETWORK  [conn58] received client metadata from 127.0.0.1:51916 conn58: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T07:04:55.764+0900 I -        [conn56] end connection 127.0.0.1:51128 (21 connections now open)
2017-12-07T07:30:45.807+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:52038 #59 (21 connections now open)
2017-12-07T07:30:45.807+0900 I NETWORK  [conn59] received client metadata from 127.0.0.1:52038 conn59: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-07T07:31:45.807+0900 I -        [conn58] end connection 127.0.0.1:51916 (21 connections now open)
