2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] MongoDB starting : pid=9798 port=57018 dbpath=/data/shard2/rs1 64-bit host=kris-ThinkPad-X1-Carbon-5th
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] db version v3.4.10
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] git version: 078f28920cb24de0dd479b5ea6c66c644f6326e9
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] allocator: tcmalloc
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] modules: none
2017-12-03T21:00:51.668+0900 I CONTROL  [initandlisten] build environment:
2017-12-03T21:00:51.669+0900 I CONTROL  [initandlisten]     distmod: ubuntu1604
2017-12-03T21:00:51.669+0900 I CONTROL  [initandlisten]     distarch: x86_64
2017-12-03T21:00:51.669+0900 I CONTROL  [initandlisten]     target_arch: x86_64
2017-12-03T21:00:51.669+0900 I CONTROL  [initandlisten] options: { net: { port: 57018 }, processManagement: { fork: true }, replication: { replSet: "s2" }, sharding: { clusterRole: "shardsvr" }, storage: { dbPath: "/data/shard2/rs1" }, systemLog: { destination: "file", path: "s2-r1.log" } }
2017-12-03T21:00:51.690+0900 I STORAGE  [initandlisten] 
2017-12-03T21:00:51.690+0900 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
2017-12-03T21:00:51.690+0900 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
2017-12-03T21:00:51.690+0900 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=7269M,session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
2017-12-03T21:00:51.773+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] ** WARNING: You are running this process as the root user, which is not recommended.
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/enabled is 'always'.
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
2017-12-03T21:00:51.774+0900 I CONTROL  [initandlisten] 
2017-12-03T21:00:51.774+0900 W SHARDING [initandlisten] Started with --shardsvr, but no shardIdentity document was found on disk in admin.system.version. This most likely means this server has not yet been added to a sharded cluster.
2017-12-03T21:00:51.794+0900 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/shard2/rs1/diagnostic.data'
2017-12-03T21:00:51.814+0900 I REPL     [initandlisten] Did not find local voted for document at startup.
2017-12-03T21:00:51.814+0900 I REPL     [initandlisten] Did not find local replica set configuration document at startup;  NoMatchingDocument: Did not find replica set configuration document in local.system.replset
2017-12-03T21:00:51.814+0900 I NETWORK  [thread1] waiting for connections on port 57018
2017-12-03T21:00:57.026+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40822 #1 (1 connection now open)
2017-12-03T21:00:57.026+0900 I -        [conn1] end connection 127.0.0.1:40822 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40826 #2 (1 connection now open)
2017-12-03T21:00:57.027+0900 I NETWORK  [conn2] received client metadata from 127.0.0.1:40826 conn2: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:57.027+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-03T21:00:57.028+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 1ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.030+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40866 #3 (2 connections now open)
2017-12-03T21:00:59.031+0900 I -        [conn3] end connection 127.0.0.1:40866 (2 connections now open)
2017-12-03T21:00:59.069+0900 I REPL     [replExecDBWorker-0] Starting replication storage threads
2017-12-03T21:00:59.135+0900 I REPL     [replication-0] Starting initial sync (attempt 1 of 10)
2017-12-03T21:00:59.135+0900 I REPL     [ReplicationExecutor] New replica set config in use: { _id: "s2", version: 1, protocolVersion: 1, members: [ { _id: 0, host: "localhost:57017", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 1, host: "localhost:57018", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 }, { _id: 2, host: "localhost:57019", arbiterOnly: false, buildIndexes: true, hidden: false, priority: 1.0, tags: {}, slaveDelay: 0, votes: 1 } ], settings: { chainingAllowed: true, heartbeatIntervalMillis: 2000, heartbeatTimeoutSecs: 10, electionTimeoutMillis: 10000, catchUpTimeoutMillis: 60000, getLastErrorModes: {}, getLastErrorDefaults: { w: 1, wtimeout: 0 }, replicaSetId: ObjectId('5a23e77974cc47503351a376') } }
2017-12-03T21:00:59.136+0900 I REPL     [ReplicationExecutor] This node is localhost:57018 in the config
2017-12-03T21:00:59.136+0900 I REPL     [ReplicationExecutor] transition to STARTUP2
2017-12-03T21:00:59.136+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57019
2017-12-03T21:00:59.136+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-03T21:00:59.137+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57019, took 1ms (1 connections now open to localhost:57019)
2017-12-03T21:00:59.138+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state STARTUP
2017-12-03T21:00:59.138+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40872 #4 (2 connections now open)
2017-12-03T21:00:59.139+0900 I NETWORK  [conn4] received client metadata from 127.0.0.1:40872 conn4: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:00:59.170+0900 I REPL     [replication-0] sync source candidate: localhost:57017
2017-12-03T21:00:59.170+0900 I STORAGE  [replication-0] dropAllDatabasesExceptLocal 1
2017-12-03T21:00:59.170+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.170+0900 I REPL     [replication-0] creating replication oplog of size: 6071MB...
2017-12-03T21:00:59.188+0900 I STORAGE  [replication-0] Starting WiredTigerRecordStoreThread local.oplog.rs
2017-12-03T21:00:59.188+0900 I STORAGE  [replication-0] The size storer reports that the oplog contains 0 records totaling to 0 bytes
2017-12-03T21:00:59.188+0900 I STORAGE  [replication-0] Scanning the oplog to determine where to place markers for truncation
2017-12-03T21:00:59.265+0900 I REPL     [replication-0] ******
2017-12-03T21:00:59.265+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.268+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (1 connections now open to localhost:57017)
2017-12-03T21:00:59.270+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:00:59.272+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-03T21:00:59.274+0900 I REPL     [replication-1] No need to apply operations. (currently at { : Timestamp 1512302457000|1 })
2017-12-03T21:00:59.274+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 1 connections to that host remain open
2017-12-03T21:00:59.275+0900 I REPL     [replication-1] Finished fetching oplog during initial sync: CallbackCanceled: Callback canceled. Last fetched optime and hash: { ts: Timestamp 1512302457000|1, t: -1 }[3144501803686678102]
2017-12-03T21:00:59.275+0900 I REPL     [replication-0] Initial sync attempt finishing up.
2017-12-03T21:00:59.275+0900 I REPL     [replication-0] Initial Sync Attempt Statistics: { failedInitialSyncAttempts: 0, maxFailedInitialSyncAttempts: 10, initialSyncStart: new Date(1512302459135), initialSyncAttempts: [], fetchedMissingDocs: 0, appliedOps: 0, initialSyncOplogStart: Timestamp 1512302457000|1, initialSyncOplogEnd: Timestamp 1512302457000|1, databases: { databasesCloned: 0 } }
2017-12-03T21:00:59.281+0900 I REPL     [replication-0] initial sync done; took 0s.
2017-12-03T21:00:59.281+0900 I REPL     [replication-0] Starting replication fetcher thread
2017-12-03T21:00:59.282+0900 I REPL     [replication-0] Starting replication applier thread
2017-12-03T21:00:59.282+0900 I REPL     [replication-0] Starting replication reporter thread
2017-12-03T21:00:59.282+0900 I REPL     [rsSync] transition to RECOVERING
2017-12-03T21:00:59.282+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-03T21:00:59.284+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state STARTUP2
2017-12-03T21:00:59.284+0900 I REPL     [rsSync] transition to SECONDARY
2017-12-03T21:01:04.284+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state SECONDARY
2017-12-03T21:01:07.549+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40902 #5 (3 connections now open)
2017-12-03T21:01:07.550+0900 I NETWORK  [conn5] received client metadata from 127.0.0.1:40902 conn5: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:01:07.550+0900 I -        [conn2] end connection 127.0.0.1:40826 (3 connections now open)
2017-12-03T21:01:09.285+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-03T21:01:10.285+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-03T21:01:10.286+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:01:10.286+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 0ms (2 connections now open to localhost:57017)
2017-12-03T21:02:10.833+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41026 #6 (3 connections now open)
2017-12-03T21:02:10.833+0900 I NETWORK  [conn6] received client metadata from 127.0.0.1:41026 conn6: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:10.911+0900 I INDEX    [repl writer worker 6] build index on: admin.system.version properties: { v: 2, key: { version: 1 }, name: "incompatible_with_version_32", ns: "admin.system.version" }
2017-12-03T21:02:10.911+0900 I INDEX    [repl writer worker 6] 	 building index using bulk method; build may temporarily use up to 500 megabytes of RAM
2017-12-03T21:02:10.913+0900 I INDEX    [repl writer worker 6] build index done.  scanned 0 total records. 0 secs
2017-12-03T21:02:10.914+0900 I COMMAND  [repl writer worker 13] setting featureCompatibilityVersion to 3.4
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 4] initializing sharding state with: { _id: "shardIdentity", configsvrConnectionString: "csReplSet/localhost:57040,localhost:57041,localhost:57042", shardName: "s2", clusterId: ObjectId('5a23e786bf51d32cbcc946a4') }
2017-12-03T21:02:10.922+0900 I SHARDING [repl writer worker 4] first cluster operation detected, adding sharding hook to enable versioning and authentication to remote servers
2017-12-03T21:02:10.923+0900 I NETWORK  [repl writer worker 4] Starting new replica set monitor for csReplSet/localhost:57040,localhost:57041,localhost:57042
2017-12-03T21:02:10.923+0900 I SHARDING [thread2] creating distributed lock ping thread for process kris-ThinkPad-X1-Carbon-5th:57018:1512302530:4551575021656647226 (sleeping for 30000ms)
2017-12-03T21:02:10.924+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I NETWORK  [shard registry reload] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-03T21:02:10.924+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.924+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-03T21:02:10.925+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.926+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (2 connections now open to localhost:57040)
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s0/localhost:37017,localhost:37018,localhost:37019
2017-12-03T21:02:10.927+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s1/localhost:47017,localhost:47018,localhost:47019
2017-12-03T21:02:10.928+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-03T21:02:10.929+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-03T21:02:10.929+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-03T21:02:10.930+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-03T21:02:10.930+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-03T21:02:10.931+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-03T21:02:10.936+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: LockStateChangeFailed: findAndModify query predicate didn't match any lock document
2017-12-03T21:02:10.983+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41136 #7 (4 connections now open)
2017-12-03T21:02:10.983+0900 I NETWORK  [conn7] received client metadata from 127.0.0.1:41136 conn7: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:11.205+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41168 #8 (5 connections now open)
2017-12-03T21:02:11.205+0900 I NETWORK  [conn8] received client metadata from 127.0.0.1:41168 conn8: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.454+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41200 #9 (6 connections now open)
2017-12-03T21:02:27.454+0900 I NETWORK  [conn9] received client metadata from 127.0.0.1:41200 conn9: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:27.611+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41218 #10 (7 connections now open)
2017-12-03T21:02:27.611+0900 I NETWORK  [conn10] received client metadata from 127.0.0.1:41218 conn10: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.683+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41250 #11 (8 connections now open)
2017-12-03T21:02:40.683+0900 I NETWORK  [conn11] received client metadata from 127.0.0.1:41250 conn11: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.684+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41256 #12 (9 connections now open)
2017-12-03T21:02:40.685+0900 I NETWORK  [conn12] received client metadata from 127.0.0.1:41256 conn12: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.827+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41264 #13 (10 connections now open)
2017-12-03T21:02:40.827+0900 I NETWORK  [conn13] received client metadata from 127.0.0.1:41264 conn13: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.832+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41270 #14 (11 connections now open)
2017-12-03T21:02:40.833+0900 I NETWORK  [conn14] received client metadata from 127.0.0.1:41270 conn14: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.851+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41278 #15 (12 connections now open)
2017-12-03T21:02:40.851+0900 I NETWORK  [conn15] received client metadata from 127.0.0.1:41278 conn15: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.928+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:02:40.930+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T21:02:40.931+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41294 #16 (13 connections now open)
2017-12-03T21:02:40.932+0900 I NETWORK  [shard registry reload] Starting new replica set monitor for s2/localhost:57017,localhost:57018,localhost:57019
2017-12-03T21:02:40.932+0900 I NETWORK  [conn16] received client metadata from 127.0.0.1:41294 conn16: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.932+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41296 #17 (14 connections now open)
2017-12-03T21:02:40.933+0900 I NETWORK  [conn17] received client metadata from 127.0.0.1:41296 conn17: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.934+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-03T21:02:40.935+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41304 #18 (15 connections now open)
2017-12-03T21:02:40.936+0900 I NETWORK  [conn18] received client metadata from 127.0.0.1:41304 conn18: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-03T21:02:40.936+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-03T21:02:40.941+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-03T21:03:10.927+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Ending idle connection to host localhost:57040 because the pool meets constraints; 1 connections to that host remain open
2017-12-03T21:06:10.937+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:06:10.937+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-03T21:12:40.954+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:12:40.954+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 0ms (1 connections now open to localhost:57041)
2017-12-03T21:13:10.955+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:13:10.956+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:20:10.970+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T21:20:10.972+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T21:26:34.178+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:26:34.179+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-03T21:27:34.178+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T21:38:41.026+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:38:41.027+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:46:41.050+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:46:41.050+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-03T21:54:11.063+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T21:54:11.064+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T21:58:14.229+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-03T21:58:14.232+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-03T21:59:14.232+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-03T22:23:11.118+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:23:11.120+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-03T22:27:11.125+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:27:11.127+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-03T22:32:41.139+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T22:32:41.140+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T22:37:11.149+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-03T22:37:11.150+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-03T23:32:41.276+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:32:41.277+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-03T23:43:11.302+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-03T23:43:11.303+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T00:27:41.416+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T00:27:41.418+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:05:41.506+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:05:41.508+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:46:41.609+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:46:41.611+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T01:55:11.632+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T01:55:11.633+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T02:00:11.647+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:00:11.648+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T02:13:11.679+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T02:13:11.680+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T03:32:11.870+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T03:32:11.872+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T03:36:41.882+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T03:36:41.884+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T04:31:24.981+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T04:31:24.981+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T04:32:24.981+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T04:46:12.063+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T04:46:12.065+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T05:58:42.245+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T05:58:42.246+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T06:05:55.178+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T06:05:55.179+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T06:06:55.178+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T06:38:12.360+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T06:38:12.362+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T07:01:42.420+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T07:01:42.425+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 5ms (1 connections now open to localhost:57041)
2017-12-04T07:29:12.490+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T07:29:12.492+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T08:05:12.585+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T08:05:12.590+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 5ms (1 connections now open to localhost:57041)
2017-12-04T15:41:54.175+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:41:54.184+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 0 connections to that host remain open
2017-12-04T15:41:54.203+0900 I REPL     [replication-0] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 134610 -- target:localhost:57017 db:local expDate:2017-12-04T08:14:55.440+0900 cmd:{ getMore: 20181560396, collection: "oplog.rs", maxTimeMS: 5000, term: 1, lastKnownCommittedOpTime: { ts: Timestamp 1512342830000|1, t: 1 } }. Last fetched optime (with hash): { ts: Timestamp 1512342830000|1, t: 1 }[2855280599495995645]. Restarts remaining: 3
2017-12-04T15:41:54.203+0900 I REPL     [replication-0] Scheduled new oplog query Fetcher source: localhost:57017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 2, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 134625 -- target:localhost:57017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512342830000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 2, readConcern: { afterOpTime: { ts: Timestamp 1512342830000|1, t: 1 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-04T15:41:54.203+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-04T15:41:54.203+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state PRIMARY
2017-12-04T15:41:54.203+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.203+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T15:41:54.210+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:45116 #19 (16 connections now open)
2017-12-04T15:41:54.210+0900 I NETWORK  [conn19] received client metadata from 127.0.0.1:45116 conn19: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T15:41:54.211+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.211+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T15:41:54.224+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 21ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.225+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 22ms (2 connections now open to localhost:57017)
2017-12-04T15:41:54.228+0900 I REPL     [replication-1] Choosing new sync source because our current sync source, localhost:57017, has an OpTime ({ ts: Timestamp 1512369714000|1, t: 1 }) which is not ahead of ours ({ ts: Timestamp 1512369714000|1, t: 1 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T15:41:54.229+0900 I REPL     [replication-1] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57017, OpTime { ts: Timestamp 1512369714000|1, t: 1 }, its sync source index:-1
2017-12-04T15:41:54.229+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57017 (config version: 1; last applied optime: { ts: Timestamp 1512369714000|1, t: 1 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T15:41:54.229+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T15:41:54.234+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-04T15:41:59.230+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57019
2017-12-04T15:41:59.231+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57019
2017-12-04T15:41:59.232+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57019, took 1ms (1 connections now open to localhost:57019)
2017-12-04T15:41:59.233+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57019
2017-12-04T15:41:59.233+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57019, took 1ms (2 connections now open to localhost:57019)
2017-12-04T15:42:10.547+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T15:42:10.549+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T15:42:10.871+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57040)
2017-12-04T15:42:10.873+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-04T15:42:10.874+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:47017)
2017-12-04T15:42:10.876+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-04T15:42:10.877+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:57017)
2017-12-04T15:42:10.879+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T15:42:10.880+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 16 secs, remote host 127.0.0.1:37017)
2017-12-04T15:42:10.881+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T15:42:40.550+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T15:42:40.551+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T15:42:54.201+0900 I -        [conn4] end connection 127.0.0.1:40872 (16 connections now open)
2017-12-04T15:42:54.225+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T15:57:41.318+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T15:57:41.322+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-04T16:06:41.342+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:06:41.343+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-04T16:45:25.187+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:34710 #20 (16 connections now open)
2017-12-04T16:45:25.187+0900 I NETWORK  [conn20] received client metadata from 127.0.0.1:34710 conn20: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T16:45:25.195+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:37018)
2017-12-04T16:45:25.195+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1094 secs, remote host 127.0.0.1:47019)
2017-12-04T16:45:25.196+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-04T16:45:25.196+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-04T16:45:25.199+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-04T16:45:25.199+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57019
2017-12-04T16:45:25.200+0900 I REPL     [ReplicationExecutor] VoteRequester(term 2 dry run) received a yes vote from localhost:57019; response message: { term: 2, voteGranted: true, reason: "", ok: 1.0 }
2017-12-04T16:45:25.200+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-04T16:45:25.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 5ms (2 connections now open to localhost:57017)
2017-12-04T16:45:25.210+0900 I REPL     [ReplicationExecutor] VoteRequester(term 3) received a no vote from localhost:57017 with reason "already voted for another candidate this term"; response message: { term: 3, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-04T16:45:25.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57019, took 16ms (2 connections now open to localhost:57019)
2017-12-04T16:45:25.218+0900 I REPL     [ReplicationExecutor] VoteRequester(term 3) received a no vote from localhost:57019 with reason "already voted for another candidate this term"; response message: { term: 3, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-04T16:45:25.218+0900 I REPL     [ReplicationExecutor] not becoming primary, we received insufficient votes
2017-12-04T16:45:25.229+0900 I REPL     [replication-0] Choosing new sync source because our current sync source, localhost:57019, has an OpTime ({ ts: Timestamp 1512372445000|1, t: 2 }) which is not ahead of ours ({ ts: Timestamp 1512372445000|1, t: 2 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T16:45:25.229+0900 I REPL     [replication-0] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57019, OpTime { ts: Timestamp 1512372445000|1, t: 2 }, its sync source index:-1
2017-12-04T16:45:25.229+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57019 (config version: 1; last applied optime: { ts: Timestamp 1512372445000|1, t: 2 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T16:45:25.229+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T16:45:25.229+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-04T16:45:25.229+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state SECONDARY
2017-12-04T16:45:25.266+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.266+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-04T16:45:25.904+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T16:45:25.904+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57019: InvalidSyncSource: Sync source was cleared. Was localhost:57019
2017-12-04T16:45:30.231+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-04T16:45:30.231+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T16:45:30.233+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (1 connections now open to localhost:57017)
2017-12-04T16:45:30.234+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T16:45:30.236+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-04T16:45:31.974+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T16:45:31.976+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T16:45:32.329+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57041)
2017-12-04T16:45:32.331+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-04T16:45:32.334+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-04T16:45:32.336+0900 W NETWORK  [ReplicaSetMonitor-TaskExecutor-0] No primary detected for set s1
2017-12-04T16:45:32.336+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 7 secs, remote host 127.0.0.1:57019)
2017-12-04T16:45:32.338+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57019 (1 connections now open to localhost:57019 with a 5 second timeout)
2017-12-04T16:45:32.342+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37018 (1 connections now open to localhost:37018 with a 5 second timeout)
2017-12-04T16:46:25.191+0900 I -        [conn20] end connection 127.0.0.1:34710 (16 connections now open)
2017-12-04T16:46:25.201+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T16:46:25.212+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57019 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T16:46:31.978+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T16:46:31.979+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T16:55:31.998+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T16:55:31.999+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 1ms (1 connections now open to localhost:57041)
2017-12-04T17:05:32.032+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T17:05:32.033+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T17:11:32.047+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T17:11:32.048+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T18:03:33.133+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T18:03:33.134+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T18:17:03.164+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-04T18:17:03.166+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-04T19:13:57.206+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 144 secs, remote host 127.0.0.1:47018)
2017-12-04T19:13:57.206+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 144 secs, remote host 127.0.0.1:57017)
2017-12-04T19:13:57.206+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 144 secs, remote host 127.0.0.1:57042)
2017-12-04T19:13:57.210+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-04T19:13:57.210+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57042 as failed :: caused by :: NotMaster: not master
2017-12-04T19:13:57.212+0900 I REPL     [replication-2] Choosing new sync source because our current sync source, localhost:57017, has an OpTime ({ ts: Timestamp 1512382437000|1, t: 3 }) which is not ahead of ours ({ ts: Timestamp 1512382437000|1, t: 3 }), it does not have a sync source, and it's not the primary (sync source does not know the primary)
2017-12-04T19:13:57.212+0900 I REPL     [replication-2] Canceling oplog query due to OplogQueryMetadata. We have to choose a new sync source. Current source: localhost:57017, OpTime { ts: Timestamp 1512382437000|1, t: 3 }, its sync source index:-1
2017-12-04T19:13:57.212+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: sync source localhost:57017 (config version: 1; last applied optime: { ts: Timestamp 1512382437000|1, t: 3 }; sync source index: -1; primary index: -1) is no longer valid
2017-12-04T19:13:57.213+0900 I REPL     [rsBackgroundSync] could not find member to sync from
2017-12-04T19:13:57.218+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-04T19:13:57.255+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57042 (1 connections now open to localhost:57042 with a 5 second timeout)
2017-12-04T19:13:57.255+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-04T19:13:57.255+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: FailedToSatisfyReadPreference: could not find host matching read preference { mode: "primary" } for set csReplSet
2017-12-04T19:13:59.652+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-04T19:14:12.217+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-04T19:14:12.218+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-04T19:14:12.219+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T19:14:12.221+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-04T19:14:12.240+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51188 #21 (16 connections now open)
2017-12-04T19:14:12.241+0900 I NETWORK  [conn21] received client metadata from 127.0.0.1:51188 conn21: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:12.244+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:51190 #22 (17 connections now open)
2017-12-04T19:14:12.244+0900 I NETWORK  [conn22] received client metadata from 127.0.0.1:51190 conn22: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T19:14:20.947+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47018 (1 connections now open to localhost:47018 with a 5 second timeout)
2017-12-04T19:14:20.949+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-04T19:14:20.950+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 23 secs, remote host 127.0.0.1:37017)
2017-12-04T19:14:20.951+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-04T19:14:24.188+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T19:14:24.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T19:15:24.190+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T19:21:20.516+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T19:21:20.518+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T19:33:20.545+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T19:33:20.547+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T19:59:54.266+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T19:59:54.272+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 6ms (3 connections now open to localhost:57017)
2017-12-04T20:00:54.267+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T20:04:04.275+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T20:04:04.279+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 4ms (3 connections now open to localhost:57017)
2017-12-04T20:05:04.278+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T20:12:04.292+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T20:12:04.296+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 5ms (3 connections now open to localhost:57017)
2017-12-04T20:13:04.296+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T20:13:54.293+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T20:13:54.296+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T20:14:54.295+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T20:29:21.369+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T20:29:21.370+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-04T21:00:29.369+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T21:00:29.372+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T21:01:29.372+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T21:12:21.470+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:12:21.472+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T21:20:54.402+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:56466 #23 (18 connections now open)
2017-12-04T21:20:54.403+0900 I NETWORK  [conn23] received client metadata from 127.0.0.1:56466 conn23: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-04T21:21:54.403+0900 I -        [conn22] end connection 127.0.0.1:51190 (18 connections now open)
2017-12-04T21:29:51.513+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T21:29:51.515+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-04T21:44:04.440+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T21:44:04.442+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-04T21:45:04.441+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T22:02:51.596+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-04T22:02:51.598+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-04T22:09:14.490+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T22:09:14.491+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T22:10:14.491+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T22:12:34.495+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T22:12:34.497+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-04T22:13:34.496+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T22:50:54.571+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T22:50:54.575+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 4ms (3 connections now open to localhost:57017)
2017-12-04T22:51:54.575+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T23:18:24.619+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-04T23:18:24.620+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-04T23:19:24.619+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-04T23:43:21.845+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-04T23:43:21.847+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T00:23:21.943+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T00:23:21.945+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T00:39:49.771+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T00:39:49.774+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-05T00:40:49.773+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T00:56:44.802+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T00:56:44.804+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T00:57:44.803+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T01:08:52.057+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:08:52.058+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:13:52.066+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:13:52.067+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:29:52.099+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T01:29:52.100+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T01:32:44.866+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T01:32:44.867+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T01:33:44.867+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T01:41:22.127+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T01:41:22.129+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T02:19:22.220+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:19:22.222+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T02:58:52.312+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T02:58:52.314+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T03:04:52.328+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:04:52.330+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 2ms (1 connections now open to localhost:57040)
2017-12-05T03:09:15.056+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T03:09:15.057+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T03:10:35.057+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T03:12:22.348+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:12:22.349+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T03:17:52.363+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:17:52.364+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T03:20:45.072+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T03:20:45.073+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T03:21:45.072+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T03:36:05.099+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:40440 #24 (18 connections now open)
2017-12-05T03:36:05.099+0900 I NETWORK  [conn24] received client metadata from 127.0.0.1:40440 conn24: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T03:37:05.099+0900 I -        [conn23] end connection 127.0.0.1:56466 (18 connections now open)
2017-12-05T03:37:45.101+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T03:37:45.102+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T03:38:25.103+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:41566 #25 (18 connections now open)
2017-12-05T03:38:25.104+0900 I NETWORK  [conn25] received client metadata from 127.0.0.1:41566 conn25: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T03:38:45.102+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T03:39:25.104+0900 I -        [conn24] end connection 127.0.0.1:40440 (18 connections now open)
2017-12-05T03:51:15.125+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T03:51:15.129+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 4ms (3 connections now open to localhost:57017)
2017-12-05T03:52:15.126+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T03:56:22.457+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T03:56:22.458+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T04:28:22.537+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:28:22.539+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 3ms (1 connections now open to localhost:57042)
2017-12-05T04:31:52.547+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T04:31:52.548+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T04:38:52.566+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T04:38:52.570+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 4ms (1 connections now open to localhost:57042)
2017-12-05T05:15:22.659+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:15:22.660+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T05:27:25.300+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T05:27:25.303+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
2017-12-05T05:28:25.301+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T05:38:15.327+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T05:38:15.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T05:39:15.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T05:42:10.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T05:42:10.329+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T05:43:10.328+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T05:47:22.725+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T05:47:22.726+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:09:05.379+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T06:09:05.381+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T06:10:05.380+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T06:23:10.400+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T06:23:10.401+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T06:24:10.400+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T06:25:22.797+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T06:25:22.798+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 1ms (1 connections now open to localhost:57042)
2017-12-05T06:35:52.818+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T06:35:52.822+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 4ms (1 connections now open to localhost:57040)
2017-12-05T07:05:15.478+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T07:05:15.480+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T07:06:15.479+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T07:16:25.494+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T07:16:25.496+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T07:17:25.495+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T07:33:22.933+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T07:33:22.933+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 0ms (1 connections now open to localhost:57042)
2017-12-05T07:37:52.942+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T07:37:52.943+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 1ms (1 connections now open to localhost:57040)
2017-12-05T07:38:35.533+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T07:38:35.534+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (3 connections now open to localhost:57017)
2017-12-05T07:39:35.534+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T07:40:45.544+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T07:40:45.546+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T07:41:45.545+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T08:04:05.582+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T08:04:05.584+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (3 connections now open to localhost:57017)
2017-12-05T15:30:53.174+0900 I REPL     [ReplicationExecutor] Starting an election, since we've seen no PRIMARY in the past 10000ms
2017-12-05T15:30:53.174+0900 I REPL     [ReplicationExecutor] conducting a dry run election to see if we could be elected
2017-12-05T15:30:53.176+0900 I COMMAND  [conn25] command local.oplog.rs command: getMore { getMore: 36306519948, collection: "oplog.rs", maxTimeMS: 5000, term: 4, lastKnownCommittedOpTime: { ts: Timestamp 1512428660000|1, t: 4 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512382437000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 4, readConcern: { afterOpTime: { ts: Timestamp 1512382437000|1, t: 3 } } } planSummary: COLLSCAN cursorid:36306519948 keysExamined:0 docsExamined:0 numYields:1 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 6 } }, Database: { acquireCount: { r: 3 } }, oplog: { acquireCount: { r: 3 } } } protocol:op_command 26782593ms
2017-12-05T15:30:53.185+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57017
2017-12-05T15:30:53.185+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Connecting to localhost:57019
2017-12-05T15:30:53.186+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 2 connections to that host remain open
2017-12-05T15:30:53.186+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:30:53.186+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57017, took 12ms (2 connections now open to localhost:57017)
2017-12-05T15:30:53.186+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending connection to host localhost:57017 due to bad connection status; 0 connections to that host remain open
2017-12-05T15:30:53.186+0900 I REPL     [ReplicationExecutor] VoteRequester(term 4 dry run) received a yes vote from localhost:57017; response message: { term: 4, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T15:30:53.186+0900 I REPL     [ReplicationExecutor] dry election run succeeded, running for election
2017-12-05T15:30:53.186+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Successfully connected to localhost:57019, took 12ms (2 connections now open to localhost:57019)
2017-12-05T15:30:53.196+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57276 #26 (18 connections now open)
2017-12-05T15:30:53.197+0900 I NETWORK  [conn26] received client metadata from 127.0.0.1:57276 conn26: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:53.204+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5) received a no vote from localhost:57019 with reason "already voted for another candidate this term"; response message: { term: 5, voteGranted: false, reason: "already voted for another candidate this term", ok: 1.0 }
2017-12-05T15:30:53.207+0900 I -        [conn25] end connection 127.0.0.1:41566 (18 connections now open)
2017-12-05T15:30:53.207+0900 I -        [conn21] end connection 127.0.0.1:51188 (17 connections now open)
2017-12-05T15:30:53.212+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:37019)
2017-12-05T15:30:53.212+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:47017)
2017-12-05T15:30:53.212+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 26790 secs, remote host 127.0.0.1:57017)
2017-12-05T15:30:53.212+0900 I REPL     [replication-4] Restarting oplog query due to error: ExceededTimeLimit: Operation timed out, request was RemoteCommand 349040 -- target:localhost:57017 db:local expDate:2017-12-05T08:05:35.582+0900 cmd:{ getMore: 17770247334, collection: "oplog.rs", maxTimeMS: 5000, term: 4, lastKnownCommittedOpTime: { ts: Timestamp 1512428670000|1, t: 4 } }. Last fetched optime (with hash): { ts: Timestamp 1512428670000|1, t: 4 }[-4572138473438295509]. Restarts remaining: 3
2017-12-05T15:30:53.212+0900 I REPL     [replication-4] Scheduled new oplog query Fetcher source: localhost:57017 database: local query: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } query metadata: { $replData: 1, $oplogQueryData: 1, $ssm: { $secondaryOk: true } } active: 1 timeout: 65000ms shutting down?: 0 first: 1 firstCommandScheduler: RemoteCommandRetryScheduler request: RemoteCommand 349064 -- target:localhost:57017 db:local cmd:{ find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } active: 1 callbackHandle.valid: 1 callbackHandle.cancelled: 0 attempt: 1 retryPolicy: RetryPolicyImpl maxAttempts: 1 maxTimeMillis: -1ms
2017-12-05T15:30:53.212+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T15:30:53.212+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T15:30:53.227+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57294 #27 (17 connections now open)
2017-12-05T15:30:53.227+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57296 #28 (18 connections now open)
2017-12-05T15:30:53.227+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 15ms (2 connections now open to localhost:57017)
2017-12-05T15:30:53.227+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 15ms (2 connections now open to localhost:57017)
2017-12-05T15:30:53.228+0900 I NETWORK  [conn28] received client metadata from 127.0.0.1:57296 conn28: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:53.228+0900 I NETWORK  [conn27] received client metadata from 127.0.0.1:57294 conn27: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] VoteRequester(term 5) received a yes vote from localhost:57017; response message: { term: 4, voteGranted: true, reason: "", ok: 1.0 }
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] election succeeded, assuming primary role in term 5
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] transition to PRIMARY
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] Entering primary catch-up mode.
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state SECONDARY
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] Caught up to the latest optime known via heartbeats after becoming primary.
2017-12-05T15:30:53.242+0900 I REPL     [ReplicationExecutor] Exited primary catch-up mode.
2017-12-05T15:30:53.243+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57041 as failed :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-05T15:30:53.243+0900 W SHARDING [replSetDistLockPinger] pinging failed for distributed lock pinger :: caused by :: PrimarySteppedDown: Primary stepped down while waiting for replication. 
2017-12-05T15:30:53.245+0900 W REPL     [rsBackgroundSync] Fetcher stopped querying remote oplog with error: InvalidSyncSource: Sync source's last applied OpTime { ts: Timestamp 1512428670000|1, t: 4 } is not greater than our last fetched OpTime { ts: Timestamp 1512428670000|1, t: 4 }. Choosing new sync source.
2017-12-05T15:30:55.176+0900 I REPL     [rsSync] transition to primary complete; database writes are now permitted
2017-12-05T15:30:58.232+0900 I REPL     [SyncSourceFeedback] SyncSourceFeedback error sending update to localhost:57017: InvalidSyncSource: Sync source was cleared. Was localhost:57017
2017-12-05T15:30:59.178+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57390 #29 (19 connections now open)
2017-12-05T15:30:59.179+0900 I NETWORK  [conn29] received client metadata from 127.0.0.1:57390 conn29: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:30:59.181+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57392 #30 (20 connections now open)
2017-12-05T15:30:59.182+0900 I NETWORK  [conn30] received client metadata from 127.0.0.1:57392 conn30: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:31:09.270+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57042
2017-12-05T15:31:09.272+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57042, took 2ms (1 connections now open to localhost:57042)
2017-12-05T15:31:10.043+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 17 secs, remote host 127.0.0.1:57041)
2017-12-05T15:31:10.045+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57041 (1 connections now open to localhost:57041 with a 5 second timeout)
2017-12-05T15:31:10.048+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47017 (1 connections now open to localhost:47017 with a 5 second timeout)
2017-12-05T15:31:10.050+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57017 (1 connections now open to localhost:57017 with a 5 second timeout)
2017-12-05T15:31:10.053+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37019 (1 connections now open to localhost:37019 with a 5 second timeout)
2017-12-05T15:31:16.232+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:57618 #31 (21 connections now open)
2017-12-05T15:31:16.233+0900 I NETWORK  [conn31] received client metadata from 127.0.0.1:57618 conn31: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T15:31:23.244+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57040
2017-12-05T15:31:23.244+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57040, took 0ms (1 connections now open to localhost:57040)
2017-12-05T15:31:53.186+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.198+0900 I -        [conn19] end connection 127.0.0.1:45116 (21 connections now open)
2017-12-05T15:31:53.204+0900 I ASIO     [NetworkInterfaceASIO-Replication-0] Ending idle connection to host localhost:57019 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T15:31:53.232+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Ending idle connection to host localhost:57017 because the pool meets constraints; 1 connections to that host remain open
2017-12-05T16:03:27.185+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32782 #32 (21 connections now open)
2017-12-05T16:03:27.195+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:37017)
2017-12-05T16:03:27.195+0900 I NETWORK  [PeriodicTaskRunner] Socket closed remotely, no longer connected (idle 1517 secs, remote host 127.0.0.1:47019)
2017-12-05T16:03:27.200+0900 I REPL     [ReplicationExecutor] Member localhost:57019 is now in state SECONDARY
2017-12-05T16:03:27.200+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32796 #33 (22 connections now open)
2017-12-05T16:03:27.201+0900 I NETWORK  [conn33] received client metadata from 127.0.0.1:32796 conn33: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.201+0900 I REPL     [ReplicationExecutor] stepping down from primary, because a new term has begun: 6
2017-12-05T16:03:27.201+0900 I REPL     [ReplicationExecutor] stepping down from primary, because a new term has begun: 6
2017-12-05T16:03:27.201+0900 I REPL     [replExecDBWorker-0] transition to SECONDARY
2017-12-05T16:03:27.201+0900 I NETWORK  [replExecDBWorker-0] legacy transport layer closing all connections
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 33
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 31
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 30
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 29
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 28
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 27
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 26
2017-12-05T16:03:27.202+0900 I NETWORK  [replExecDBWorker-0] Skip closing connection for connection # 5
2017-12-05T16:03:27.202+0900 I -        [conn9] end connection 127.0.0.1:41200 (22 connections now open)
2017-12-05T16:03:27.202+0900 I -        [conn13] end connection 127.0.0.1:41264 (21 connections now open)
2017-12-05T16:03:27.202+0900 I -        [conn11] end connection 127.0.0.1:41250 (20 connections now open)
2017-12-05T16:03:27.202+0900 I -        [conn10] end connection 127.0.0.1:41218 (19 connections now open)
2017-12-05T16:03:27.202+0900 I -        [conn18] end connection 127.0.0.1:41304 (18 connections now open)
2017-12-05T16:03:27.203+0900 I -        [conn5] end connection 127.0.0.1:40902 (17 connections now open)
2017-12-05T16:03:27.205+0900 I -        [conn7] end connection 127.0.0.1:41136 (16 connections now open)
2017-12-05T16:03:27.206+0900 I -        [conn6] end connection 127.0.0.1:41026 (15 connections now open)
2017-12-05T16:03:27.206+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32808 #34 (8 connections now open)
2017-12-05T16:03:27.206+0900 I NETWORK  [conn34] received client metadata from 127.0.0.1:32808 conn34: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.207+0900 I -        [conn8] end connection 127.0.0.1:41168 (15 connections now open)
2017-12-05T16:03:27.207+0900 I -        [conn16] end connection 127.0.0.1:41294 (14 connections now open)
2017-12-05T16:03:27.207+0900 I -        [conn12] end connection 127.0.0.1:41256 (13 connections now open)
2017-12-05T16:03:27.207+0900 I -        [conn15] end connection 127.0.0.1:41278 (12 connections now open)
2017-12-05T16:03:27.207+0900 I -        [conn14] end connection 127.0.0.1:41270 (11 connections now open)
2017-12-05T16:03:27.207+0900 I -        [conn17] end connection 127.0.0.1:41296 (10 connections now open)
2017-12-05T16:03:27.215+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32822 #35 (9 connections now open)
2017-12-05T16:03:27.215+0900 I NETWORK  [conn35] received client metadata from 127.0.0.1:32822 conn35: { driver: { name: "NetworkInterfaceASIO-Replication", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:27.219+0900 I -        [conn32] end connection 127.0.0.1:32782 (10 connections now open)
2017-12-05T16:03:27.228+0900 I COMMAND  [conn30] command local.oplog.rs command: getMore { getMore: 35395374028, collection: "oplog.rs", maxTimeMS: 5000, term: 5, lastKnownCommittedOpTime: { ts: Timestamp 1512455885000|1, t: 5 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } planSummary: COLLSCAN cursorid:35395374028 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 658 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1517025ms
2017-12-05T16:03:27.228+0900 I COMMAND  [conn27] command local.oplog.rs command: getMore { getMore: 36241397699, collection: "oplog.rs", maxTimeMS: 5000, term: 5, lastKnownCommittedOpTime: { ts: Timestamp 1512455885000|1, t: 5 } } originatingCommand: { find: "oplog.rs", filter: { ts: { $gte: Timestamp 1512428670000|1 } }, tailable: true, oplogReplay: true, awaitData: true, maxTimeMS: 60000, term: 5, readConcern: { afterOpTime: { ts: Timestamp 1512428670000|1, t: 4 } } } planSummary: COLLSCAN cursorid:36241397699 keysExamined:0 docsExamined:0 numYields:0 nreturned:0 reslen:563 locks:{ Global: { acquireCount: { r: 4 }, acquireWaitCount: { r: 1 }, timeAcquiringMicros: { r: 843 } }, Database: { acquireCount: { r: 2 } }, oplog: { acquireCount: { r: 2 } } } protocol:op_command 1517025ms
2017-12-05T16:03:27.229+0900 I -        [conn26] end connection 127.0.0.1:57276 (9 connections now open)
2017-12-05T16:03:27.233+0900 I NETWORK  [replSetDistLockPinger] Marking host localhost:57040 as failed :: caused by :: NotMaster: Not primary while running findAndModify command on collection config.lockpings
2017-12-05T16:03:27.233+0900 I NETWORK  [replSetDistLockPinger] Detected bad connection created at 1512369730872190 microSec, clearing pool for localhost:57040 of 0 connections
2017-12-05T16:03:27.233+0900 I NETWORK  [replSetDistLockPinger] Dropping all pooled connections to localhost:57040(with timeout of 5 seconds)
2017-12-05T16:03:27.233+0900 I NETWORK  [replSetDistLockPinger] Ending connection to host localhost:57040(with timeout of 5 seconds) due to bad connection status; 0 connections to that host remain open
2017-12-05T16:03:27.234+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:27.674+0900 I -        [conn29] end connection 127.0.0.1:57390 (8 connections now open)
2017-12-05T16:03:27.674+0900 I -        [conn28] end connection 127.0.0.1:57296 (7 connections now open)
2017-12-05T16:03:27.735+0900 I NETWORK  [replSetDistLockPinger] Successfully connected to localhost:57040 (1 connections now open to localhost:57040 with a 5 second timeout)
2017-12-05T16:03:27.736+0900 W NETWORK  [replSetDistLockPinger] No primary detected for set csReplSet
2017-12-05T16:03:29.201+0900 I REPL     [ReplicationExecutor] Member localhost:57017 is now in state PRIMARY
2017-12-05T16:03:29.236+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32868 #36 (7 connections now open)
2017-12-05T16:03:29.236+0900 I NETWORK  [conn36] received client metadata from 127.0.0.1:32868 conn36: { driver: { name: "NetworkInterfaceASIO-ShardRegistry", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:30.191+0900 I REPL     [rsBackgroundSync] sync source candidate: localhost:57017
2017-12-05T16:03:30.191+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T16:03:30.192+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 1ms (1 connections now open to localhost:57017)
2017-12-05T16:03:30.199+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T16:03:30.201+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 2ms (2 connections now open to localhost:57017)
2017-12-05T16:03:33.234+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32914 #37 (8 connections now open)
2017-12-05T16:03:33.234+0900 I NETWORK  [conn37] received client metadata from 127.0.0.1:32914 conn37: { driver: { name: "NetworkInterfaceASIO-RS", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.319+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32978 #38 (9 connections now open)
2017-12-05T16:03:39.319+0900 I NETWORK  [conn38] received client metadata from 127.0.0.1:32978 conn38: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.450+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32984 #39 (10 connections now open)
2017-12-05T16:03:39.450+0900 I NETWORK  [conn39] received client metadata from 127.0.0.1:32984 conn39: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:39.480+0900 I -        [conn31] end connection 127.0.0.1:57618 (10 connections now open)
2017-12-05T16:03:39.942+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:32994 #40 (10 connections now open)
2017-12-05T16:03:39.942+0900 I NETWORK  [conn40] received client metadata from 127.0.0.1:32994 conn40: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.148+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33116 #41 (11 connections now open)
2017-12-05T16:03:52.149+0900 I NETWORK  [conn41] received client metadata from 127.0.0.1:33116 conn41: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.150+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33118 #42 (12 connections now open)
2017-12-05T16:03:52.151+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33120 #43 (13 connections now open)
2017-12-05T16:03:52.151+0900 I NETWORK  [conn42] received client metadata from 127.0.0.1:33118 conn42: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.151+0900 I NETWORK  [conn43] received client metadata from 127.0.0.1:33120 conn43: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.163+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33128 #44 (14 connections now open)
2017-12-05T16:03:52.164+0900 I NETWORK  [conn44] received client metadata from 127.0.0.1:33128 conn44: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.485+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33138 #45 (15 connections now open)
2017-12-05T16:03:52.486+0900 I NETWORK  [conn45] received client metadata from 127.0.0.1:33138 conn45: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.494+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33146 #46 (16 connections now open)
2017-12-05T16:03:52.494+0900 I NETWORK  [conn46] received client metadata from 127.0.0.1:33146 conn46: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.538+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33150 #47 (17 connections now open)
2017-12-05T16:03:52.538+0900 I NETWORK  [conn47] received client metadata from 127.0.0.1:33150 conn47: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.542+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33158 #48 (18 connections now open)
2017-12-05T16:03:52.542+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33160 #49 (19 connections now open)
2017-12-05T16:03:52.542+0900 I NETWORK  [conn48] received client metadata from 127.0.0.1:33158 conn48: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.543+0900 I NETWORK  [conn49] received client metadata from 127.0.0.1:33160 conn49: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.545+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:47019 (1 connections now open to localhost:47019 with a 5 second timeout)
2017-12-05T16:03:52.546+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Socket closed remotely, no longer connected (idle 25 secs, remote host 127.0.0.1:57018)
2017-12-05T16:03:52.547+0900 I NETWORK  [thread1] connection accepted from 127.0.0.1:33170 #50 (20 connections now open)
2017-12-05T16:03:52.547+0900 I NETWORK  [conn50] received client metadata from 127.0.0.1:33170 conn50: { driver: { name: "MongoDB Internal Client", version: "3.4.10" }, os: { type: "Linux", name: "LinuxMint", architecture: "x86_64", version: "18.3" } }
2017-12-05T16:03:52.548+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:57018 (1 connections now open to localhost:57018 with a 5 second timeout)
2017-12-05T16:03:52.550+0900 I NETWORK  [ReplicaSetMonitor-TaskExecutor-0] Successfully connected to localhost:37017 (1 connections now open to localhost:37017 with a 5 second timeout)
2017-12-05T16:04:27.234+0900 I -        [conn35] end connection 127.0.0.1:32822 (20 connections now open)
2017-12-05T16:04:32.172+0900 I COMMAND  [ftdc] serverStatus was very slow: { after basic: 0, after asserts: 0, after backgroundFlushing: 0, after connections: 0, after dur: 0, after extra_info: 0, after globalLock: 0, after locks: 0, after network: 0, after opLatencies: 0, after opcounters: 0, after opcountersRepl: 0, after repl: 0, after security: 0, after storageEngine: 0, after tcmalloc: 0, after wiredTiger: 1289, at end: 1299 }
2017-12-05T16:05:53.043+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Connecting to localhost:57041
2017-12-05T16:05:53.045+0900 I ASIO     [NetworkInterfaceASIO-ShardRegistry-0] Successfully connected to localhost:57041, took 2ms (1 connections now open to localhost:57041)
2017-12-05T16:08:27.236+0900 I -        [conn30] end connection 127.0.0.1:57392 (19 connections now open)
2017-12-05T16:08:39.267+0900 I -        [conn36] end connection 127.0.0.1:32868 (18 connections now open)
2017-12-05T16:25:04.241+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Connecting to localhost:57017
2017-12-05T16:25:04.244+0900 I ASIO     [NetworkInterfaceASIO-RS-0] Successfully connected to localhost:57017, took 3ms (3 connections now open to localhost:57017)
